project:
  type: website
  output-dir: docs

website:
  title: "BSTA 511/611 Fall 2023"
  navbar:
    background: primary
    search: true
    logo: "images/IMG_8165sq_med.png"
    foreground: "#fff"
    collapse-below: sm
    left:
      - href: index.qmd
        text: Home

  sidebar:
    style: "docked"
    search: true
    collapse-level: 4
    contents:
      - href: index.qmd
        text: Home
      - section: "Course Info"
        contents:
          - href: instructors.qmd
            text: Instructors        
format:
  html:
    theme: yeti
    css: styles.css
    toc: true



