project:
  type: website
  output-dir: docs

website:
  title: "BSTA 511/611 Fall 2023"
  navbar:
    background: primary
    search: true
    logo: "images/IMG_8165sq_med.png"
    foreground: "#fff"
    collapse-below: sm
    right:
      - href: index.qmd
        text: Home
      - href: class_slides.qmd
        text: Slides
      - href: weeks.qmd
        text: Weeks
      - href: about.qmd
        text: About
  sidebar:
    style: "docked"
    search: true
    collapse-level: 4
    contents:
      - href: index.qmd
        text: Home
      - href: instructors.qmd
        text: Instructors        
      - href: class_slides.qmd
        text: Slides
      - href: weeks.qmd
        text: Weeks
            
format:
  html:
    theme: yeti
    css: styles.css
    toc: true



