---
title: "Week 7"
description: "Inference for difference in means, one proportion, and difference in proportions, and power"
date: "11/6/2023"
date-modified: "today"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---


## Day11 

* Inference for difference in means from two independent sample (2-sample t-test)
* Power and sample size calculations

### Slides

* [html](../slides/Day11_bsta511.qmd) 
    * Draft version
        * Slides 1-26 on two-sample inference for difference in means are done
            * Videos (parts 1 & 2) are posted
        * Slides 27-45 on power and sample size still need some tweaking, but the material is mainly there. 
            * Video (part 3) will be posted early Saturday
* [pdf](https://drive.google.com/file/d/1JurHC3FjbKZ-k5TkDHr9qh7VryCwi3SY/view?usp=sharing)
    * Draft version (see html for details)
* Slides with [notes](https://drive.google.com/file/d/1cOxfjLuZ5NwU-_zxzQHnJxz0ZCryuCSC/view?usp=sharing)
    * Draft: currently only includes two-sample inference (video parts 1 & 2)

<!-- * [webpage](../slides_md/Day11_bsta511_md.qmd) -->

* Code file: [qmd](https://github.com/niederhausen/BSTA_511_F23/blob/main/slides_code/Day11_bsta511_code.qmd), [html](../slides_code/Day11_bsta511_code.qmd)
    * Draft version (see html for details)


### Datasets

All datasets can be found on [GitHub](https://github.com/niederhausen/BSTA_511_F23/tree/main/data)

* [CaffeineTaps.csv](/data/CaffeineTaps.csv)


### Class discussion

[Class discussion Google doc link](https://docs.google.com/document/d/1m_sOZWZHlnL89N60RyfdFG6wphcEpofLevd2kMc1wYc/edit?usp=sharing)

* TBD - will be posted early Saturday morning


## Day12    

* Inference for proportions
    * CIs vs. hypothesis tests
    * One proportion from one sample
    * Difference in proportions from two independent samples

### Slides - coming soon!

<!-- * [html](../slides/Day12_part1_bsta511.qmd) -->
<!-- * [pdf]() -->
<!-- * Slides with [notes]() -->
<!-- * [webpage](../slides_md/Day12_part1_bsta511_md.qmd) -->
<!-- * Code file: [qmd](https://github.com/niederhausen/BSTA_511_F23/blob/main/slides_code/Day12_part1_bsta511_code.qmd), [html](../slides_code/Day12_part1_bsta511_code.qmd) -->




### Class discussion

[Class discussion Google doc link](https://docs.google.com/document/d/1m_sOZWZHlnL89N60RyfdFG6wphcEpofLevd2kMc1wYc/edit?usp=sharing)

* 

## Homework

* [HW 6](../homework/HW_6_F23_bsta511.qmd) due on Sat, 11/11
    * Coming soon!
    * Covers Days 11-12



## Recordings

* __Pre-recorded__ lessons are on [Echo Cloud](https://echo360.org/section/4a58d645-5753-4e4f-b962-f8825f59baba/home) (aka echo 360 or echo video).
    * These can be accessed in Sakai by navigating to the BSTA 511/611 page and clicking on the `Echo Cloud` option in the left-side menu. 
    * This will redirect you to an echo video page with a list of pre-recorded videos.
* __In-class__ recording links are on [Sakai](https://sakai.ohsu.edu/portal/site/BSTA-511-1-AA-F23/tool/1f70eae0-e36a-4052-9247-69c6917e6b73/). Navigate to _Course Materials_ -> _Schedule with links to in-class recordings_. Note that the password to the recordings is at the top of the page.  
