---
title: "Week 2"
description: "Intro to R & RStudio"
date: "10/2/2023"
date-modified: "9/29/2023"
categories: [""]
format: 
  html:
    link-external-newwindow: true
    toc: true
editor_options: 
  chunk_output_type: console
---



## Day02 

* Data collection & numerical summaries
* Sections 1.1-1.4

### Slides

* [html](../slides/Day02_bsta511.qmd)
* [pdf](https://drive.google.com/drive/folders/1I5-e1Dbso2jBYm5oIbMV0FqdpM-0q8pn)
* [webpage](../slides_md/Day02_bsta511_md.qmd)
* [qmd](https://github.com/niederhausen/BSTA_511_F23/blob/main/slides_md/Day02_bsta511_md.qmd)

### Recordings

* __Pre-recorded__ lessons are on Echo Cloud (aka echo 360 or echo video).
    * These can be accessed in Sakai by navigating to the BSTA 511/611 page and clicking on the `Echo Cloud` option in the left-side menu. 
    * This will redirect you to an echo video page with a list of pre-recorded videos.
* __In-class__ recording links are on Sakai. Navigate to _Course Materials_ -> _Schedule with links to in-class recordings_. Note that the password to the recordings is at the top of the page.  

### Class discussion

Please look over the following topics. We will be discussing these in class. 

* Slide 45: __Robust estimates__
* HW 1 
    * Book problems: 1.8, 1.20, 1.31
* R packages: any difficulty installing packages?

## Day03 

* Data visualization, exploratory data analysis (EDA), and summarizing categorical data
* Sections 1.5-1.7 & supplementary material

## Homework

### Slides - coming soon!

* [HW 1](../homework/HW_1_F23_bsta511.qmd) due on Sat, 10/7



