{
  "hash": "d2bc4daa01631366a6c238ecef433846",
  "result": {
    "markdown": "---\ntitle: \"DRAFT: Day 12: Inference for a single proportion or difference of two (independent) proportions (Sections 8.1-8.2)\"\nsubtitle: \"BSTA 511/611\"\nauthor: \"Meike Niederhausen, PhD\"\ninstitute: \"OHSU-PSU School of Public Health\"\ndate: \"11/8/2023\"\ncategories: [\"Week 7\"]\nformat: \n  html:\n    link-external-newwindow: true\n    toc: true\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\n# editor: visual\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n## Load packages\n\n* Packages need to be loaded _every time_ you restart R or render an Qmd file\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run these every time you open Rstudio\nlibrary(tidyverse)    \nlibrary(oibiostat)\nlibrary(janitor)\nlibrary(rstatix)\nlibrary(knitr)\nlibrary(gtsummary)\nlibrary(moderndive)\nlibrary(gt)\nlibrary(broom) \nlibrary(here) \nlibrary(pwr) # new-ish\n```\n:::\n\n\n\n- You can check whether a package has been loaded or not \n  - by looking at the Packages tab and \n  - seeing whether it has been checked off or not\n\n\n# Where are we?\n\n$$point~estimate \\pm z^*(or~t^*)\\cdot SE,~~~~~~~~test~stat = \\frac{point~estimate-null~value}{SE}$$\n\nDay | Book | Population <br> parameter | Symbol | Point estimate | Symbol | SE \n--------|--------|--------|--------|--------|--------|--------\n11-12 | 5.1 | Pop mean | $p$ | Sample mean | $\\bar{x}$ | $\\frac{s}{\\sqrt{n}}$ \n13 | 5.2 | Diff in paired <br> pop means | $p_d$ or $\\delta$ | Diff in paired <br> sample means | $\\bar{x}_{d}$  | $\\frac{s_d}{\\sqrt{n}}$ \n14 | 5.3 | Diff in pop <br> means | $p_1-p_2$ | Diff in sample <br> means | $\\bar{x}_1 - \\bar{x}_2$  | $\\sqrt{\\frac{s_1^2}{n_1} + \\frac{s_2^2}{n_2}}$ or pooled\n<span style=\"color:darkorange\">15</span> | <span style=\"color:darkorange\">8.1</span> | <span style=\"color:darkorange\">Pop proportion</span> | $p$ | <span style=\"color:darkorange\">Sample prop</span> | $\\hat{p}$  | \n<span style=\"color:darkorange\">15</span> | <span style=\"color:darkorange\">8.2</span> | <span style=\"color:darkorange\">Diff in pop <br> proportions</span> | $p_1-p_2$ | <span style=\"color:darkorange\">Diff in sample <br> proportions</span> | $\\hat{p}_1-\\hat{p}_2$ | \n\n\n\n\n\n\n# Goals for today (Sections 8.1-8.2)\n\n* Statistical inference for a single proportion or the difference of two (independent) proportions\n    1. Sampling distribution for a proportion or difference in proportions\n    \n    1. What are $H_0$ and $H_a$?\n    \n    1. What are the SE's for $\\hat{p}$ and $\\hat{p}_1-\\hat{p}_2$?\n    \n    1. Hypothesis test\n    \n    1. Confidence Interval\n    \n    1. How are the SE's different for a hypothesis test & CI?\n    \n    1. Run test in R\n\n\n\n# Motivating example\n\n__One proportion__\n\n* A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year. \n    * What is the CI for the proportion?\n    * The study also reported that 36% of noncollege young males had participated in sports betting. Is the proportion for male college students different from 0.36?\n\n__Two proportions__\n\n* There were 214 men in the sample of noncollege young males (36% participated in sports betting in the previous year).\n* Compare the difference in proportions between the college and noncollege young males.\n    * CI\n    * Hypothesis test\n\n\nBarnes GM, Welte JW, Hoffman JH, Tidwell MC. [Comparisons of gambling and alcohol use among college students and noncollege young people in the United States](https://www.tandfonline.com/doi/full/10.1080/07448480903540499?journalCode=vach20). J Am Coll Health. 2010 Mar-Apr;58(5):443-52. doi: 10.1080/07448480903540499. PMID: 20304756; PMCID: PMC4104810.\n\n\n\n\n## Steps in a Hypothesis Test\n\n1. Set the __[level of significance]{style=\"color:darkorange\"}__ $\\alpha$\n\n1. Specify the __[null]{style=\"color:darkorange\"}__ ( $H_0$ ) and __[alternative]{style=\"color:darkorange\"}__ ( $H_A$ ) __[hypotheses]{style=\"color:darkorange\"}__\n    1. In symbols\n    1. In words\n    1. Alternative: one- or two-sided?\n\n1. Calculate the __[test statistic]{style=\"color:darkorange\"}__. \n\n1. Calculate the __[p-value]{style=\"color:darkorange\"}__ based on the observed test statistic and its sampling distribution\n\n1. Write a __[conclusion]{style=\"color:darkorange\"}__ to the hypothesis test\n    1. Do we reject or fail to reject $H_0$?\n    1. Write a conclusion in the context of the problem\n\n\n# Step 2: Null & Alternative Hypotheses \n\nNull and alternative hypotheses in __words__ and in __symbols__.\n\n\n__One sample test__\n\n* $H_0$: The population proportion of young male college students that participated in sports betting in the previous year is 0.36.\n\n* $H_A$: The population proportion of young male college students that participated in sports betting in the previous year is not 0.36.\n\n$$~~~~H_0: p = 0.36\\\\\nH_A: p \\neq 0.36$$\n\n\n\n__Two samples test__\n\n* $H_0$: The difference in population proportions of young male college and noncollege students that participated in sports betting in the previous year is 0.\n\n* $H_A$: The difference in population proportions of young male college and noncollege students that participated in sports betting in the previous year is not 0.\n\n$$~~~~H_0: p_{coll} - p_{noncoll} = 0\\\\\nH_A: p_{coll} - p_{noncoll} \\neq 0$$\n\n\n\n# One proportion inference\n\n## Sampling distribution of $\\hat{p}$ \n\n* $\\hat{p}=\\frac{X}{n}$ where $X$ is the number of \"successes\" and $n$ is the sample size.\n* Thus, $X \\sim Bin(n,p)$, where $p$ is the population proportion.\n* For $n$ \"big enough\", the normal distribution can be used to approximate a binomial distribution:\n\n$$Bin(n,p) \\rightarrow N\\Big(\\mu = np, \\sigma = \\sqrt{np(1-p)} \\Big)$$\n* Since $\\hat{p}=\\frac{X}{n}$ is a linear transformation of $X$, we have for large n: \n\n$$\\hat{p} \\sim N\\Big(\\mu_{\\hat{p}} = p, \\sigma_{\\hat{p}} = \\sqrt{\\frac{p(1-p)}{n}} \\Big)$$\n\n* How we apply this result to CI's and test statistics is different!!!\n\n\n\n\n## Step 3: Test statistic \n\n\nSampling distribution of $\\hat{p}$\n$$\\hat{p} \\sim N\\Big(\\mu_{\\hat{p}} = p, \\sigma_{\\hat{p}} = \\sqrt{\\frac{p(1-p)}{n}} \\Big)$$\nIf we assume $H_0: p=p_0$ is true, then  \n\n$$\\hat{p} \\sim N\\Big(\n\\mu_{\\hat{p}}=p_0, \\sigma_{\\hat{p}}=\\sqrt{\\frac{p_0\\cdot(1-p_0)}{n}}\n\\Big)$$\n\n\n\n\n\nGeneral test statistic:\n\n$$\n\\text{test statistic} = \\frac{point~estimate - null~value}{SE}\n$$\n\nFor a one sample proportion test:\n\n$$\n\\text{test statistic} = z_{\\hat{p}} = \\frac{\\hat{p} - p_0}{\\sqrt{\\frac{p_0\\cdot(1-p_0)}{n}}}\n$$\n\n\n<hr>\n\n\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year.   \nWhat is the test statistic when testing $H_0: p=0.36$ vs. \n$H_A: p \\neq 0.36$? \n\n\n\n\n\n\n\n\n$$z_{\\hat{p}} = \\frac{94/269 - 0.36}{\\sqrt{\\frac{0.36\\cdot(1-0.36)}{269}}}$$\n\n\n\n\n\n\n## Step \"3b\": Conditions satisfied?\n\n\n__Conditions__:\n\n1. _Independent observations_ \n    * The observations were collected independently.\n\n1. The number of __expected successes and expected failures is at least 10__.\n    * $n_1 p_0 \\ge 10, \\ \\ n_1(1-p_0)\\ge 10$\n\n\n\n\n\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year.   \nTesting $H_0: p=0.36$ vs. $H_A: p \\neq 0.36$.  \nAre the conditions satisfied?\n\n\n\n\n## Step 4: p-value\n\nThe __[p-value]{style=\"color:darkorange\"}__ is the __probability__ of obtaining a test statistic _just as extreme or more extreme_ than the observed test statistic assuming the null hypothesis $H_0$ is true. \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day12_bsta511_code_files/figure-html/unnamed-chunk-4-1.png){width=384}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day12_bsta511_code_files/figure-html/unnamed-chunk-5-1.png){width=384}\n:::\n:::\n\n\n\n\n\n\n\nCalculate the _p_-value:\n\n\n$$2 \\cdot P(\\hat{p}<0.35) \\\\\n= 2 \\cdot P\\Big(Z_{\\hat{p}} < \\frac{94/269 - 0.36}{\\sqrt{\\frac{0.36\\cdot(1-0.36)}{269}}}\\Big)\\\\\n=2 \\cdot P(Z_{\\hat{p}} < -0.3607455)$$\n\n::: {.cell}\n\n```{.r .cell-code}\n2*pnorm(-0.3607455)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7182897\n```\n:::\n:::\n\n\n\n\n## Step 5: Conclusion to hypothesis test\n\n$$~~~~H_0: p = 0.36\\\\\nH_A: p \\neq 0.36$$\n\n* Recall the $p$-value = 0.7182897\n* Use $\\alpha$ = 0.05.\n* Do we reject or fail to reject $H_0$?\n\n__Conclusion statement__:\n\n* Stats class conclusion\n    * There is insufficient evidence that the (population) proportion of young male college students that participated in sports betting in the previous year is different than 0.36 ( $p$-value = 0.72).\n\n* More realistic manuscript conclusion: \n    * In a sample of 269 male college students, 35% had participated in sports betting in the previous year, which is not different from 36% ( $p$-value = 0.72).\n\n\n\n## 95% CI for population proportion\n\nWhat to use for SE in CI formula?\n\n$$\\hat{p} \\pm z^* \\cdot SE_{\\hat{p}}$$\n\nSampling distribution of $\\hat{p}$\n$$\\hat{p} \\sim N\\Big(\\mu_{\\hat{p}} = p, \\sigma_{\\hat{p}} = \\sqrt{\\frac{p(1-p)}{n}} \\Big)$$\n\n\n\n<hr>\n\n\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year.   \nFind the 95% CI for the population proportion. \n\n\n$$94/269 \\pm 1.96 \\cdot SE_{\\hat{p}}\\\\\nSE_{\\hat{p}} = \\sqrt{\\frac{(94/269)(1-94/269)}{269}}$$\n\n\n__Interpretation__:  \nWe are 95% confident that the (population) proportion of young male college students that participated in sports betting in the previous year is in (0.29, 0.41).\n\n\n\n## Conditions for one proportion: test vs. CI\n\n\n__Hypothesis test conditions__\n\n1. _Independent observations_ \n    * The observations were collected independently.\n\n1. The number of __expected__ successes and __expected__ failures is at least 10.\n\n$$n_1 p_0 \\ge 10, \\ \\ n_1(1-p_0)\\ge 10$$\n\n\n\n__Confidence interval conditions__\n\n1. _Independent observations_ \n    * The observations were collected independently.\n\n1. The number of successes and failures is at least 10:\n\n$$n_1\\hat{p}_1 \\ge 10, \\ \\ n_1(1-\\hat{p}_1)\\ge 10$$\n\n\n# Two (independent) proportions inference\n\n\n## Sampling distribution of $\\hat{p}_1-\\hat{p}_2$ \n\n* $\\hat{p}_1=\\frac{X_1}{n_1}$ and $\\hat{p}_2=\\frac{X_2}{n_2}$, where $X_1$ & $X_2$ are the number of \"successes\" and $n_1$ & $n_2$ are the sample sizes of the 1st & 2nd samples, with population proportions $p_1$ & $p_2$, respectively.\n* On the previous slide we saw that $\\hat{p}$ can be approximated by a normal distribution.\n* Since the difference of independent normal random variables is also independent, it follows that for $n_1$ and $n_2$ \"big enough\"\n\n$$\\hat{p}_1 - \\hat{p}_2 \\sim N \\Big(\\mu_{\\hat{p}_1 - \\hat{p}_2} = p_1 - p_2, ~~\n\\sigma_{\\hat{p}_1 - \\hat{p}_2} =\n\\sqrt{\n\\frac{p_1\\cdot(1-p_1)}{n_1} + \\frac{p_2\\cdot(1-p_2)}{n_2}} \n\\Big)$$\n\n* How we apply this result to CI's and test statistics is different!!!\n\n\n\n## Step 3: Test statistic (1/2)\n\nSampling distribution of $\\hat{p}_1 - \\hat{p}_2$:\n$$\\hat{p}_1 - \\hat{p}_2 \\sim N \\Big(\\mu_{\\hat{p}_1 - \\hat{p}_2} = p_1 - p_2, ~~\n\\sigma_{\\hat{p}_1 - \\hat{p}_2} =\n\\sqrt{\n\\frac{p_1\\cdot(1-p_1)}{n_1} + \\frac{p_2\\cdot(1-p_2)}{n_2}} \n\\Big)$$\n\nIf we assume $H_0: p_1=p_2$ is true, then we \"pool\" the proportions of the two samples to calculate the SE:\n\n$$pooled~proportion = \\hat{p} = \\dfrac{\\text{total number of successes} }{ \\text{total number of cases}} = \\frac{x_1+x_2}{n_1+n_2}$$ \n\n\nTest statistic:\n\n$$\n\\text{test statistic} = z_{\\hat{p}_1 - \\hat{p}_2} = \\frac{\\hat{p}_1 - \\hat{p}_2 - 0}{\\sqrt{\\frac{\\hat{p}\\cdot(1-\\hat{p})}{n_1} + \\frac{\\hat{p}\\cdot(1-\\hat{p})}{n_2}}}\n$$\n\n\n\n\n## Step 3: Test statistic (2/2)\n\n\n$$\n\\text{test statistic} = z_{\\hat{p}_1 - \\hat{p}_2} = \\frac{\\hat{p}_1 - \\hat{p}_2 - 0}{\\sqrt{\\frac{\\hat{p}\\cdot(1-\\hat{p})}{n_1} + \\frac{\\hat{p}\\cdot(1-\\hat{p})}{n_2}}}\n$$\n$$pooled~proportion = \\hat{p} = \\dfrac{\\text{total number of successes} }{ \\text{total number of cases}} = \\frac{x_1+x_2}{n_1+n_2}$$ \n<hr>\n\n\n\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year, and out of 214 noncollege young males 36% had.  \nWhat is the test statistic when testing $H_0: p_{coll} - p_{noncoll} = 0$ vs. \n$H_A: p_{coll} - p_{noncoll} \\neq 0$? \n\n\n\n$$z_{\\hat{p}_1 - \\hat{p}_2} = \\frac{94/269 - 77/214-0}{\\sqrt{0.354\\cdot(1-0.354)(\\frac{1}{269}+\\frac{1}{214})}}\\\\\n=-0.2367497$$\n\n\n\n\n## Step \"3b\": Conditions satisfied?\n\n\n__Conditions__:\n\n* _Independent observations & samples_\n    * The observations were collected independently. \n    * In particular, observations from the two groups weren't paired in any meaningful way.\n\n* The number of expected successes and expected failures is at least 10 _for each group_ - using the pooled proportion:\n    * $n_1\\hat{p} \\ge 10, \\ \\ n_1(1-\\hat{p}) \\ge 10$\n    * $n_2\\hat{p} \\ge 10, \\ \\ n_2(1-\\hat{p}) \\ge 10$\n\n\n\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year, and out of 214 noncollege young males 36% had.   \nTesting $H_0: p_{coll} - p_{noncoll} = 0$ vs. \n$H_A: p_{coll} - p_{noncoll} \\neq 0$? .  \nAre the conditions satisfied?\n\n\n## Step 4: p-value\n\nThe __[p-value]{style=\"color:darkorange\"}__ is the __probability__ of obtaining a test statistic _just as extreme or more extreme_ than the observed test statistic assuming the null hypothesis $H_0$ is true. \n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day12_bsta511_code_files/figure-html/unnamed-chunk-7-1.png){width=384}\n:::\n:::\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day12_bsta511_code_files/figure-html/unnamed-chunk-8-1.png){width=384}\n:::\n:::\n\n\n\nCalculate the _p_-value:\n\n$$2 \\cdot P(\\hat{p}_1 - \\hat{p}_2<0.35-0.36) \\\\\n= 2 \\cdot P\\Big(Z_{\\hat{p}_1 - \\hat{p}_2} < \\\\\n\\frac{94/269 - 77/214-0}{\\sqrt{0.354\\cdot(1-0.354)(\\frac{1}{269}+\\frac{1}{214})}}\\Big)\\\\\n=2 \\cdot P(Z_{\\hat{p}} < -0.2367497)$$\n\n::: {.cell}\n\n```{.r .cell-code}\n2*pnorm(-0.2367497)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.812851\n```\n:::\n:::\n\n\n\n\n\n## Step 5: Conclusion to hypothesis test\n\n$$~~~~H_0: p_{coll} - p_{noncoll} = 0\\\\\nH_A: p_{coll} - p_{noncoll} \\neq 0$$\n\n* Recall the $p$-value = 0.812851\n* Use $\\alpha$ = 0.05.\n* Do we reject or fail to reject $H_0$?\n\n__Conclusion statement__:\n\n* Stats class conclusion\n    * There is insufficient evidence that the difference in (population) proportions of young male college and noncollege students that participated in sports betting in the previous year are different ( $p$-value = 0.81).\n\n* More realistic manuscript conclusion: \n    * 35% of young male college students (n=269) and 36% of noncollege young males (n=214) participated in sports betting in the previous year ( $p$-value = 0.81).\n\n\n\n## 95% CI for population difference in proportions\n\n\n\nWhat to use for SE in CI formula?\n\n$$\\hat{p}_1 - \\hat{p}_2 \\pm z^* \\cdot SE_{\\hat{p}_1 - \\hat{p}_2}$$\n\n\n\nSE in sampling distribution of $\\hat{p}_1 - \\hat{p}_2$\n$$\\sigma_{\\hat{p}_1 - \\hat{p}_2} =\n\\sqrt{\n\\frac{p_1\\cdot(1-p_1)}{n_1} + \\frac{p_2\\cdot(1-p_2)}{n_2}} $$\n\n\n\n<hr>\n\n\n__Example:__ A 2010 study found that out of 269 male college students, 35% had participated in sports betting in the previous year, and out of 214 noncollege young males 36% had.\nFind the 95% CI for the difference in population proportions. \n\n$$\\frac{94}{269} - \\frac{77}{214} \\pm 1.96 \\cdot SE_{\\hat{p}_1 - \\hat{p}_2}$$\n\n\n$$SE_{\\hat{p}_1 - \\hat{p}_2}=\\\\\n\\sqrt{\n\\frac{94/269 \\cdot (1-94/269)}{269} + \n\\frac{77/214 \\cdot (1-77/214)}{214}}$$\n\n\n\n\n__Interpretation__:  \nWe are 95% confident that the difference in (population) proportions of young male college and noncollege students that participated in sports betting in the previous year is in (-0.127, 0.106).\n\n\n\n\n## Conditions for difference in proportions: test vs. CI\n\n\n__Hypothesis test conditions__\n\n1. _Independent observations & samples_\n    * The observations were collected independently. \n    * In particular, observations from the two groups weren't paired in any meaningful way.\n\n1. The number of expected successes and expected failures is at least 10 _for each group_ - using the pooled proportion:\n    * $n_1\\hat{p} \\ge 10, \\ \\ n_1(1-\\hat{p}) \\ge 10$\n    * $n_2\\hat{p} \\ge 10, \\ \\ n_2(1-\\hat{p}) \\ge 10$\n\n\n\n\n__Confidence interval conditions__\n\n1. _Independent observations & samples_\n    * The observations were collected independently. \n    * In particular, observations from the two groups weren't paired in any meaningful way.\n\n1. The number of expected successes and expected failures is at least 10 _for each group_.\n    * $n_1\\hat{p}_1 \\ge 10, \\ \\ n_1(1-\\hat{p}_1) \\ge 10$\n    * $n_2\\hat{p}_2 \\ge 10, \\ \\ n_2(1-\\hat{p}_2) \\ge 10$\n\n\n# R: 1-sample proportion test (1/3)\n\n\nWe first need a dataset based on the results:\n\n::: {.cell}\n\n```{.r .cell-code}\n.35*269 # number of \"successes\"\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 94.15\n```\n:::\n\n```{.r .cell-code}\n# round this value\n\nSportsBet1 <- tibble(\n  Coll = c(rep(\"Bet\", 94), \n              rep(\"NotBet\",269-94))\n  )\nglimpse(SportsBet1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 269\nColumns: 1\n$ Coll <chr> \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"Bet\", \"B…\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nSportsBet1 %>% tabyl(Coll)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Coll   n   percent\n    Bet  94 0.3494424\n NotBet 175 0.6505576\n```\n:::\n:::\n\n\nR code for proportions test requires input as a base R `table`:\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(SportsBet1$Coll)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n   Bet NotBet \n    94    175 \n```\n:::\n:::\n\n\n\n\n\n\n\n## R: 1-sample proportion test (2/3)\n\n`prop.test` requires the input x to be a table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = table(SportsBet1$Coll),\n       alternative = \"two.sided\",\n       p = 0.36,\n       correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t1-sample proportions test without continuity correction\n\ndata:  table(SportsBet1$Coll), null probability 0.36\nX-squared = 0.13014, df = 1, p-value = 0.7183\nalternative hypothesis: true p is not equal to 0.36\n95 percent confidence interval:\n 0.2949476 0.4081767\nsample estimates:\n        p \n0.3494424 \n```\n:::\n:::\n\n\n\n\n\n## R: 1-sample proportion test: with vs. without CC (3/3)\n\nApply a continuity correction (CC) to the p-value calculation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = table(SportsBet1$Coll), alternative = \"two.sided\",\n       p = 0.36, correct = FALSE) %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"mzjcizplkz\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#mzjcizplkz table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#mzjcizplkz thead, #mzjcizplkz tbody, #mzjcizplkz tfoot, #mzjcizplkz tr, #mzjcizplkz td, #mzjcizplkz th {\n  border-style: none;\n}\n\n#mzjcizplkz p {\n  margin: 0;\n  padding: 0;\n}\n\n#mzjcizplkz .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#mzjcizplkz .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#mzjcizplkz .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#mzjcizplkz .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#mzjcizplkz .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mzjcizplkz .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mzjcizplkz .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#mzjcizplkz .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#mzjcizplkz .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#mzjcizplkz .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#mzjcizplkz .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#mzjcizplkz .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#mzjcizplkz .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#mzjcizplkz .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#mzjcizplkz .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#mzjcizplkz .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#mzjcizplkz .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#mzjcizplkz .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#mzjcizplkz .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzjcizplkz .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#mzjcizplkz .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#mzjcizplkz .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#mzjcizplkz .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzjcizplkz .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#mzjcizplkz .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#mzjcizplkz .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mzjcizplkz .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzjcizplkz .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#mzjcizplkz .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mzjcizplkz .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#mzjcizplkz .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#mzjcizplkz .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mzjcizplkz .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzjcizplkz .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#mzjcizplkz .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#mzjcizplkz .gt_left {\n  text-align: left;\n}\n\n#mzjcizplkz .gt_center {\n  text-align: center;\n}\n\n#mzjcizplkz .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#mzjcizplkz .gt_font_normal {\n  font-weight: normal;\n}\n\n#mzjcizplkz .gt_font_bold {\n  font-weight: bold;\n}\n\n#mzjcizplkz .gt_font_italic {\n  font-style: italic;\n}\n\n#mzjcizplkz .gt_super {\n  font-size: 65%;\n}\n\n#mzjcizplkz .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#mzjcizplkz .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#mzjcizplkz .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#mzjcizplkz .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#mzjcizplkz .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#mzjcizplkz .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#mzjcizplkz .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.1301373</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.7182897</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.2949476</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.4081767</td>\n<td headers=\"method\" class=\"gt_row gt_left\">1-sample proportions test without continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n\n```{.r .cell-code}\nprop.test(x = table(SportsBet1$Coll), alternative = \"two.sided\",\n       p = 0.36, correct = TRUE) %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"qopayuieeo\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#qopayuieeo table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#qopayuieeo thead, #qopayuieeo tbody, #qopayuieeo tfoot, #qopayuieeo tr, #qopayuieeo td, #qopayuieeo th {\n  border-style: none;\n}\n\n#qopayuieeo p {\n  margin: 0;\n  padding: 0;\n}\n\n#qopayuieeo .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#qopayuieeo .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#qopayuieeo .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#qopayuieeo .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#qopayuieeo .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qopayuieeo .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qopayuieeo .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#qopayuieeo .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#qopayuieeo .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#qopayuieeo .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#qopayuieeo .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#qopayuieeo .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#qopayuieeo .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#qopayuieeo .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#qopayuieeo .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#qopayuieeo .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#qopayuieeo .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#qopayuieeo .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#qopayuieeo .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qopayuieeo .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#qopayuieeo .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#qopayuieeo .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#qopayuieeo .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qopayuieeo .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#qopayuieeo .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#qopayuieeo .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qopayuieeo .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qopayuieeo .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#qopayuieeo .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qopayuieeo .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#qopayuieeo .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#qopayuieeo .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qopayuieeo .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qopayuieeo .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#qopayuieeo .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#qopayuieeo .gt_left {\n  text-align: left;\n}\n\n#qopayuieeo .gt_center {\n  text-align: center;\n}\n\n#qopayuieeo .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#qopayuieeo .gt_font_normal {\n  font-weight: normal;\n}\n\n#qopayuieeo .gt_font_bold {\n  font-weight: bold;\n}\n\n#qopayuieeo .gt_font_italic {\n  font-style: italic;\n}\n\n#qopayuieeo .gt_super {\n  font-size: 65%;\n}\n\n#qopayuieeo .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#qopayuieeo .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#qopayuieeo .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#qopayuieeo .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#qopayuieeo .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#qopayuieeo .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#qopayuieeo .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">0.3494424</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.08834805</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.7662879</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">0.2931841</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.4100774</td>\n<td headers=\"method\" class=\"gt_row gt_left\">1-sample proportions test with continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nDifferences are small when sample sizes are large.\n\n\n\n\n# R: 2-samples proportions test (1/3)\n\n\nWe first need a dataset based on the results:\n\n\n::: {.cell}\n\n```{.r .cell-code}\n.35*269 # number of \"successes\"\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 94.15\n```\n:::\n\n```{.r .cell-code}\n.36*214 # round these value\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 77.04\n```\n:::\n\n```{.r .cell-code}\nSportsBet2 <- tibble(\n  Group = c(rep(\"College\", 269), \n         rep(\"NonCollege\", 214)),\n  Bet = c(rep(\"yes\", 94), \n          rep(\"no\", 269-94),\n          rep(\"yes\", 77), \n          rep(\"no\", 214-77))\n)\nglimpse(SportsBet2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 483\nColumns: 2\n$ Group <chr> \"College\", \"College\", \"College\", \"College\", \"College\", \"College\"…\n$ Bet   <chr> \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"yes\", \"…\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nSportsBet2 %>% tabyl(Group, Bet)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      Group  no yes\n    College 175  94\n NonCollege 137  77\n```\n:::\n:::\n\n\nR code for proportions test requires input as a base R `table`:\n\n::: {.cell}\n\n```{.r .cell-code}\ntable(SportsBet2$Group, SportsBet2$Bet)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n            \n              no yes\n  College    175  94\n  NonCollege 137  77\n```\n:::\n:::\n\n\n\n\n\n\n\n## R: 2-samples proportions test (2/3)\n\n`prop.test` requires the input x to be a table\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = table(SportsBet2$Group, SportsBet2$Bet),\n       alternative = \"two.sided\",\n       correct = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\t2-sample test for equality of proportions without continuity correction\n\ndata:  table(SportsBet2$Group, SportsBet2$Bet)\nX-squared = 0.05605, df = 1, p-value = 0.8129\nalternative hypothesis: two.sided\n95 percent confidence interval:\n -0.07554399  0.09628540\nsample estimates:\n   prop 1    prop 2 \n0.6505576 0.6401869 \n```\n:::\n:::\n\n\n\n\n\n## R: 2-samples proportions test: with vs. without CC (3/3)\n\nApply a continuity correction (CC) to the p-value calculation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprop.test(x = table(SportsBet2$Group, SportsBet2$Bet), alternative = \"two.sided\", \n          correct = FALSE) %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"wdojgotmqn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wdojgotmqn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wdojgotmqn thead, #wdojgotmqn tbody, #wdojgotmqn tfoot, #wdojgotmqn tr, #wdojgotmqn td, #wdojgotmqn th {\n  border-style: none;\n}\n\n#wdojgotmqn p {\n  margin: 0;\n  padding: 0;\n}\n\n#wdojgotmqn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wdojgotmqn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wdojgotmqn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wdojgotmqn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wdojgotmqn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wdojgotmqn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wdojgotmqn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wdojgotmqn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wdojgotmqn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wdojgotmqn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wdojgotmqn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wdojgotmqn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wdojgotmqn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wdojgotmqn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wdojgotmqn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wdojgotmqn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wdojgotmqn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wdojgotmqn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wdojgotmqn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wdojgotmqn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wdojgotmqn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wdojgotmqn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wdojgotmqn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wdojgotmqn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wdojgotmqn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wdojgotmqn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wdojgotmqn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wdojgotmqn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wdojgotmqn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wdojgotmqn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wdojgotmqn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wdojgotmqn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wdojgotmqn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wdojgotmqn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wdojgotmqn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wdojgotmqn .gt_left {\n  text-align: left;\n}\n\n#wdojgotmqn .gt_center {\n  text-align: center;\n}\n\n#wdojgotmqn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wdojgotmqn .gt_font_normal {\n  font-weight: normal;\n}\n\n#wdojgotmqn .gt_font_bold {\n  font-weight: bold;\n}\n\n#wdojgotmqn .gt_font_italic {\n  font-style: italic;\n}\n\n#wdojgotmqn .gt_super {\n  font-size: 65%;\n}\n\n#wdojgotmqn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wdojgotmqn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wdojgotmqn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wdojgotmqn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wdojgotmqn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wdojgotmqn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wdojgotmqn .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate1\">estimate1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate2\">estimate2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate1\" class=\"gt_row gt_right\">0.6505576</td>\n<td headers=\"estimate2\" class=\"gt_row gt_right\">0.6401869</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.05605044</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.8128509</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-0.07554399</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.0962854</td>\n<td headers=\"method\" class=\"gt_row gt_left\">2-sample test for equality of proportions without continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n\n```{.r .cell-code}\nprop.test(x = table(SportsBet2$Group, SportsBet2$Bet), alternative = \"two.sided\", \n          correct = TRUE) %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"yzphsurvzj\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#yzphsurvzj table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#yzphsurvzj thead, #yzphsurvzj tbody, #yzphsurvzj tfoot, #yzphsurvzj tr, #yzphsurvzj td, #yzphsurvzj th {\n  border-style: none;\n}\n\n#yzphsurvzj p {\n  margin: 0;\n  padding: 0;\n}\n\n#yzphsurvzj .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#yzphsurvzj .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#yzphsurvzj .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#yzphsurvzj .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#yzphsurvzj .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yzphsurvzj .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yzphsurvzj .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#yzphsurvzj .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#yzphsurvzj .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#yzphsurvzj .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#yzphsurvzj .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#yzphsurvzj .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#yzphsurvzj .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#yzphsurvzj .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#yzphsurvzj .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#yzphsurvzj .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#yzphsurvzj .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#yzphsurvzj .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#yzphsurvzj .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzphsurvzj .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#yzphsurvzj .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#yzphsurvzj .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#yzphsurvzj .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzphsurvzj .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#yzphsurvzj .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#yzphsurvzj .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yzphsurvzj .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzphsurvzj .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#yzphsurvzj .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yzphsurvzj .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#yzphsurvzj .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#yzphsurvzj .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yzphsurvzj .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzphsurvzj .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#yzphsurvzj .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#yzphsurvzj .gt_left {\n  text-align: left;\n}\n\n#yzphsurvzj .gt_center {\n  text-align: center;\n}\n\n#yzphsurvzj .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#yzphsurvzj .gt_font_normal {\n  font-weight: normal;\n}\n\n#yzphsurvzj .gt_font_bold {\n  font-weight: bold;\n}\n\n#yzphsurvzj .gt_font_italic {\n  font-style: italic;\n}\n\n#yzphsurvzj .gt_super {\n  font-size: 65%;\n}\n\n#yzphsurvzj .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#yzphsurvzj .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#yzphsurvzj .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#yzphsurvzj .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#yzphsurvzj .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#yzphsurvzj .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#yzphsurvzj .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate1\">estimate1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate2\">estimate2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate1\" class=\"gt_row gt_right\">0.6505576</td>\n<td headers=\"estimate2\" class=\"gt_row gt_right\">0.6401869</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">0.01987511</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.8878864</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">1</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">-0.07973918</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">0.1004806</td>\n<td headers=\"method\" class=\"gt_row gt_left\">2-sample test for equality of proportions with continuity correction</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">two.sided</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nDifferences are small when sample sizes are large.\n\n\n# Power & sample size for testing proportions\n",
    "supporting": [
      "Day12_bsta511_code_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}