{
  "hash": "ecb27d30c3203ad5dd7a39602490dae9",
  "result": {
    "markdown": "---\ntitle: \"DRAFT: Day 11: Inference for difference in means from two independent samples and Power (Sections 5.3, 5.4)\"\nsubtitle: \"BSTA 511/611\"\nauthor: \"Meike Niederhausen, PhD\"\ninstitute: \"OHSU-PSU School of Public Health\"\ndate: \"11/6/2023\"\ncategories: [\"Week 7\"]\nformat: \n  html:\n    link-external-newwindow: true\n    toc: true\nexecute:\n  echo: true\n  freeze: auto  # re-render only when source changes\n# editor: visual\neditor_options: \n  chunk_output_type: console\n---\n\n\n\n\n## Load packages\n\n* Packages need to be loaded _every time_ you restart R or render an Qmd file\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# run these every time you open Rstudio\nlibrary(tidyverse)    \nlibrary(oibiostat)\nlibrary(janitor)\nlibrary(rstatix)\nlibrary(knitr)\nlibrary(gtsummary)\nlibrary(moderndive)\nlibrary(gt)\nlibrary(broom) # NEW!!\nlibrary(here) # NEW!!\n```\n:::\n\n\n\n- You can check whether a package has been loaded or not \n  - by looking at the Packages tab and \n  - seeing whether it has been checked off or not\n\n\n\n\n\n# MoRitz's tip of the day: Code folding!\n\nSee the new option `code_folding: show` in the yaml above (in the .Rmd file).\n\n\n# Where are we?\n\nCI's and hypothesis tests for different scenarios:\n\n$$\\text{point estimate} \\pm z^*(or~t^*)\\cdot SE,~~\\text{test stat} = \\frac{\\text{point estimate}-\\text{null value}}{SE}$$\n\nDay | Book | Population <br> parameter | Symbol | Point estimate | Symbol | SE\n--|--|--|--|--|--|--\n10 | 5.1 | Pop mean | $\\mu$ | Sample mean | $\\bar{x}$ | $\\frac{s}{\\sqrt{n}}$\n10 | 5.2 | Pop mean of paired diff | $\\mu_d$ or $\\delta$ | Sample mean of paired diff | $\\bar{x}_{d}$  | **$\\frac{s_d}{\\sqrt{n}}$**\n11 | 5.3 | [Diff in pop <br> means]{style=\"color:green\"} | [$\\mu_1-\\mu_2$]{style=\"color:green\"} | [Diff in sample <br> means]{style=\"color:green\"} | [$\\bar{x}_1 - \\bar{x}_2$]{style=\"color:green\"}  | [**???**]{style=\"color:red\"}\n12 | 8.1 | Pop proportion | $p$ | Sample prop | $\\widehat{p}$  |\n12 | 8.2 | Diff in pop <br> proportions | $p_1-p_2$ | Diff in sample <br> proportions | $\\widehat{p}_1-\\widehat{p}_2$ |\n\n\n## Goals for today (Section 5.3)\n\n* Statistical inference for difference in means from 2 independent samples\n    1. What are $H_0$ and $H_a$?\n    \n    1. What is the SE for $\\bar{x}_1 - \\bar{x}_2$?\n    \n    1. Hypothesis test\n    \n    1. Confidence Interval\n    \n    1. Run test in R - using long vs. wide data\n    \n    1. Satterthwaite's df\n    \n    1. Pooled SD\n\n\n## Examples of designs with two independent samples\n\n* Any study where participants are randomized to a control and treatment group\n\n* Study where create two groups based on whether they were exposed or not to some condition (can be observational)\n\n*  Book: \"Does treatment using embryonic stem cells (ESCs) help improve heart function following a heart attack?\"\n\n*  Book: \"Is there evidence that newborns from mothers who smoke have a different average birth weight than newborns from mothers who do not smoke?\"\n\n\n* _The key is that the data from the two groups are independent of each other._\n\n\n## Steps in a Hypothesis Test\n\n1. Set the __[level of significance]{style=\"color:darkorange\"}__ $\\alpha$\n\n1. Specify the __[null]{style=\"color:darkorange\"}__ ( $H_0$ ) and __[alternative]{style=\"color:darkorange\"}__ ( $H_A$ ) __[hypotheses]{style=\"color:darkorange\"}__\n    1. In symbols\n    1. In words\n    1. Alternative: one- or two-sided?\n\n1. Calculate the __[test statistic]{style=\"color:darkorange\"}__. \n\n1. Calculate the __[p-value]{style=\"color:darkorange\"}__ based on the observed test statistic and its sampling distribution\n\n1. Write a __[conclusion]{style=\"color:darkorange\"}__ to the hypothesis test\n    1. Do we reject or fail to reject $H_0$?\n    1. Write a conclusion in the context of the problem\n\n\n\n# Does caffeine increase finger taps/min (on average)?\n\n__Study Design__:\n\n* 20 male college students students were trained to tap their fingers at a rapid rate.\n* Each then drank 2 cups of coffee (double-blind)\n    * __Control__ group: decaf\n    * __Caffeine__ group: ~ 200 mg caffeine \n* After 2 hours, students were tested.\n* __Taps/minute__ recorded\n\nHand, David J.; Daly, Fergus; McConway, K.; Lunn, D. and Ostrowski, E. (1993). [A handbook of small data sets](https://www.crcpress.com/A-Handbook-of-Small-Data-Sets/Hand-Daly-McConway-Lunn-Ostrowski/p/book/9780412399206). London, U.K.: Chapman and Hall.\n\n\n\n* Load the data from the csv file `CaffeineTaps.csv`\n* The code below is for when the data file is in a folder called `data` that is in your R project folder (your working directory)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nCaffTaps <- read_csv(here::here(\"data\", \"CaffeineTaps.csv\"))\n\nglimpse(CaffTaps)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 20\nColumns: 2\n$ Taps  <dbl> 246, 248, 250, 252, 248, 250, 246, 248, 245, 250, 242, 245, 244,…\n$ Group <chr> \"Caffeine\", \"Caffeine\", \"Caffeine\", \"Caffeine\", \"Caffeine\", \"Caf…\n```\n:::\n:::\n\n\n\n## EDA: Explore the finger taps data\n\nDotplot of taps/minute stratified by group\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(CaffTaps, aes(x=Taps)) +\n  geom_dotplot() +\n  facet_wrap(vars(Group), ncol=1)\n```\n\n::: {.cell-output-display}\n![](Day11_bsta511_code_files/figure-html/unnamed-chunk-4-1.png){width=480}\n:::\n:::\n\n\nSummary statistics stratified by group\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# get_summary_stats() from rstatix package\nsumstats <- CaffTaps %>% \n  group_by(Group) %>% \n  get_summary_stats(type = \"mean_sd\") \nsumstats %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"wyxtcgkfuq\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#wyxtcgkfuq table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#wyxtcgkfuq thead, #wyxtcgkfuq tbody, #wyxtcgkfuq tfoot, #wyxtcgkfuq tr, #wyxtcgkfuq td, #wyxtcgkfuq th {\n  border-style: none;\n}\n\n#wyxtcgkfuq p {\n  margin: 0;\n  padding: 0;\n}\n\n#wyxtcgkfuq .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#wyxtcgkfuq .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#wyxtcgkfuq .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#wyxtcgkfuq .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#wyxtcgkfuq .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wyxtcgkfuq .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyxtcgkfuq .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#wyxtcgkfuq .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#wyxtcgkfuq .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#wyxtcgkfuq .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#wyxtcgkfuq .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#wyxtcgkfuq .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#wyxtcgkfuq .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#wyxtcgkfuq .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#wyxtcgkfuq .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#wyxtcgkfuq .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#wyxtcgkfuq .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#wyxtcgkfuq .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#wyxtcgkfuq .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyxtcgkfuq .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#wyxtcgkfuq .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#wyxtcgkfuq .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#wyxtcgkfuq .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyxtcgkfuq .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#wyxtcgkfuq .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#wyxtcgkfuq .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyxtcgkfuq .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyxtcgkfuq .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#wyxtcgkfuq .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyxtcgkfuq .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#wyxtcgkfuq .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#wyxtcgkfuq .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wyxtcgkfuq .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyxtcgkfuq .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#wyxtcgkfuq .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#wyxtcgkfuq .gt_left {\n  text-align: left;\n}\n\n#wyxtcgkfuq .gt_center {\n  text-align: center;\n}\n\n#wyxtcgkfuq .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#wyxtcgkfuq .gt_font_normal {\n  font-weight: normal;\n}\n\n#wyxtcgkfuq .gt_font_bold {\n  font-weight: bold;\n}\n\n#wyxtcgkfuq .gt_font_italic {\n  font-style: italic;\n}\n\n#wyxtcgkfuq .gt_super {\n  font-size: 65%;\n}\n\n#wyxtcgkfuq .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#wyxtcgkfuq .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#wyxtcgkfuq .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#wyxtcgkfuq .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#wyxtcgkfuq .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#wyxtcgkfuq .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#wyxtcgkfuq .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Group\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean\">mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd\">sd</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Group\" class=\"gt_row gt_left\">Caffeine</td>\n<td headers=\"variable\" class=\"gt_row gt_center\">Taps</td>\n<td headers=\"n\" class=\"gt_row gt_right\">10</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">248.3</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">2.214</td></tr>\n    <tr><td headers=\"Group\" class=\"gt_row gt_left\">NoCaffeine</td>\n<td headers=\"variable\" class=\"gt_row gt_center\">Taps</td>\n<td headers=\"n\" class=\"gt_row gt_right\">10</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">244.8</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">2.394</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n\n```{.r .cell-code}\ndiff(sumstats$mean)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -3.5\n```\n:::\n:::\n\n\n\n\n# Step 2: Null & Alternative Hypotheses \n\n* __Question__: Is there evidence to support that drinking caffeine increases the number of finger taps/min?\n\nNull and alternative hypotheses in __words__\n\n*Include as much context as possible*\n\n\n* $H_0$: The population difference in mean finger taps/min between the caffeine and control groups is ... \n\n* $H_A$: The population difference in mean finger taps/min between the caffeine and control groups is ...\n\n\nNull and alternative hypotheses in __symbols__\n\n\\begin{align}\nH_0:& \\mu_{caff} - \\mu_{ctrl} = \\\\\nH_A:& \\mu_{caff} - \\mu_{ctrl} \\\\\n\\end{align}\n\n\n\n# Step 3: Test statistic (part 1)\n\nRecall that in general the test statistic has the form:\n\n$$\\text{test stat} = \\frac{\\text{point estimate}-\\text{null value}}{SE}$$\nThus, for a two sample independent means test, we have:\n\n$$\\text{test statistic} = \\frac{\\bar{x}_1 - \\bar{x}_2 - 0}{SE_{\\bar{x}_1 - \\bar{x}_2}}$$\n\n* What is the formula for $SE_{\\bar{x}_1 - \\bar{x}_2}$?\n* What is the probability distribution of the test statistic?\n* What assumptions need to be satisfied?\n\n\n## What distribution does $\\bar{X}_1 - \\bar{X}_2$ have?\n\n\nLet $\\bar{X}_1$ and $\\bar{X}_2$ be the means of random samples from two independent groups, with parameters:\n\n | Group 1 | Group 2 | \n--------|--------|--------|\nsample size | $n_1$| $n_2$ |\npop mean | $\\mu_1$| $\\mu_2$ |\npop sd | $\\sigma_1$| $\\sigma_2$ |\n\n\nSome theoretical statistics:\n\n* If $\\bar{X}_1$ and $\\bar{X}_2$ are independent normal r.v.'s, then $\\bar{X}_1 - \\bar{X}_2$ is also normal\n* What is the mean of $\\bar{X}_1 - \\bar{X}_2$? \n\n$$E[\\bar{X}_1 - \\bar{X}_2] = E[\\bar{X}_1] - E[\\bar{X}_2] = \\mu_1-\\mu_2$$\n\n* What is the standard deviation of $\\bar{X}_1 - \\bar{X}_2$?\n\n$$Var(\\bar{X}_1 - \\bar{X}_2) = Var(\\bar{X}_1) + Var(\\bar{X}_2) = \\frac{\\sigma_1^2}{n_1}+\\frac{\\sigma_2^2}{n_2} \\\\\nSD(\\bar{X}_1 - \\bar{X}_2) = \\sqrt{\\frac{\\sigma_1^2}{n_1}+\\frac{\\sigma_2^2}{n_2}}$$\n\n\n\n## Step 3: Test statistic (part 2)\n\n\n$$\n\\text{test statistic} = t_{\\bar{x}_1 - \\bar{x}_2} = \\frac{\\bar{x}_1 - \\bar{x}_2 - 0}{\\sqrt{\\frac{s_1^2}{n_1} + \\frac{s_2^2}{n_2}}}\n$$\n\n* $\\bar{x}_1, \\bar{x}_2$ are the sample means\n* $\\mu_0=0$ is the mean value specified in $H_0$\n* $s_1, s_2$ are the sample SD's\n* $n_1, n_2$ are the sample sizes\n\n* Statistical theory tells us that $t_{\\bar{x}_1 - \\bar{x}_2}$ follows a __student's t-distribution__ with \n    * $df \\approx$ smaller of $n_1-1$ and $n_2-1$\n    * this is a conservative estimate (smaller than actual $df$ )\n\n__Assumptions__:\n\n* __Independent observations & samples__\n    * The observations were collected independently. \n    * In particular, the observations from the two groups were not paired in any meaningful way.\n* __Approximately normal samples or big n's__ \n    * The distributions of the samples should be approximately normal \n    * _or_ _both_ their sample sizes should be at least 30.\n\n\n## Step 3: Test statistic (part 3)\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"xaavwsuvtt\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#xaavwsuvtt table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#xaavwsuvtt thead, #xaavwsuvtt tbody, #xaavwsuvtt tfoot, #xaavwsuvtt tr, #xaavwsuvtt td, #xaavwsuvtt th {\n  border-style: none;\n}\n\n#xaavwsuvtt p {\n  margin: 0;\n  padding: 0;\n}\n\n#xaavwsuvtt .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#xaavwsuvtt .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#xaavwsuvtt .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#xaavwsuvtt .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#xaavwsuvtt .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xaavwsuvtt .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xaavwsuvtt .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#xaavwsuvtt .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#xaavwsuvtt .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#xaavwsuvtt .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#xaavwsuvtt .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#xaavwsuvtt .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#xaavwsuvtt .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#xaavwsuvtt .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#xaavwsuvtt .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#xaavwsuvtt .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#xaavwsuvtt .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#xaavwsuvtt .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#xaavwsuvtt .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xaavwsuvtt .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#xaavwsuvtt .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#xaavwsuvtt .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#xaavwsuvtt .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xaavwsuvtt .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#xaavwsuvtt .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#xaavwsuvtt .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xaavwsuvtt .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xaavwsuvtt .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#xaavwsuvtt .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xaavwsuvtt .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#xaavwsuvtt .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#xaavwsuvtt .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xaavwsuvtt .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xaavwsuvtt .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#xaavwsuvtt .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#xaavwsuvtt .gt_left {\n  text-align: left;\n}\n\n#xaavwsuvtt .gt_center {\n  text-align: center;\n}\n\n#xaavwsuvtt .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#xaavwsuvtt .gt_font_normal {\n  font-weight: normal;\n}\n\n#xaavwsuvtt .gt_font_bold {\n  font-weight: bold;\n}\n\n#xaavwsuvtt .gt_font_italic {\n  font-style: italic;\n}\n\n#xaavwsuvtt .gt_super {\n  font-size: 65%;\n}\n\n#xaavwsuvtt .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#xaavwsuvtt .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#xaavwsuvtt .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#xaavwsuvtt .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#xaavwsuvtt .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#xaavwsuvtt .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#xaavwsuvtt .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Group\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean\">mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd\">sd</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Group\" class=\"gt_row gt_left\">Caffeine</td>\n<td headers=\"variable\" class=\"gt_row gt_center\">Taps</td>\n<td headers=\"n\" class=\"gt_row gt_right\">10</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">248.3</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">2.214</td></tr>\n    <tr><td headers=\"Group\" class=\"gt_row gt_left\">NoCaffeine</td>\n<td headers=\"variable\" class=\"gt_row gt_center\">Taps</td>\n<td headers=\"n\" class=\"gt_row gt_right\">10</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">244.8</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">2.394</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n$$\n\\text{test statistic} = t_{\\bar{x}_1 - \\bar{x}_2} = \\frac{\\bar{x}_1 - \\bar{x}_2 - 0}{\\sqrt{\\frac{s_1^2}{n_1} + \\frac{s_2^2}{n_2}}}\n$$\n\n\n\n\n\n\n\n\n<hr>\n\nBased on the value of the test statistic, do you think we are going to reject or fail to reject $H_0$?\n\n\n## Step \"3b\": Assumptions satisfied?\n\n__Assumptions__:\n\n* __Independent observations & samples__\n    * The observations were collected independently. \n    * In particular, the observations from the two groups were not paired in any meaningful way.\n\n* __Approximately normal samples or big n's__ \n    * The distributions of the samples should be approximately normal \n    * _or_ _both_ their sample sizes should be at least 30.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(CaffTaps, aes(x=Taps)) +\n  geom_dotplot() +\n  facet_wrap(vars(Group), ncol=1)\n```\n\n::: {.cell-output-display}\n![](Day11_bsta511_code_files/figure-html/unnamed-chunk-8-1.png){width=480}\n:::\n:::\n\n\n\nThe __[p-value]{style=\"color:darkorange\"}__ is the __probability__ of obtaining a test statistic _just as extreme or more extreme_ than the observed test statistic assuming the null hypothesis $H_0$ is true. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# specify upper and lower bounds of shaded region below\nmu <- 0\nstd <- se\n\n# The following figure is only an approximation of the \n# sampling distribution since I used a normal instead\n# of t-distribution to make it.\n\nggplot(data.frame(x = c(mu-5*std, mu+5*std)), aes(x = x)) + \n  stat_function(fun = dnorm, \n                args = list(mean = mu, sd = std)) + \n  scale_y_continuous(breaks = NULL) +\n  scale_x_continuous(breaks=c(mu, mu - 1*(1:5), mu + 1*(1:5))) +\n  theme(axis.text.x=element_text(angle = -30, hjust = 0)) +\n  labs(y = \"\", \n       x = \"difference in means\",\n       title = \"Sampling distribution of difference in means\") +\n  geom_vline(xintercept = c(diff_x), \n             color = \"red\")\n```\n\n::: {.cell-output-display}\n![](Day11_bsta511_code_files/figure-html/unnamed-chunk-9-1.png){width=480}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data = data.frame(x = c(-5, 5)), aes(x)) + \n  stat_function(fun = dt, args = list(df = min(n1 -1, n2-1))) + \n  ylab(\"\") + \n  xlab(\"t-dist with df = 9\") +\n  scale_y_continuous(breaks = NULL) + \n  scale_x_continuous(breaks=c(mu, mu - (1:5), mu + (1:5))) +\n  geom_vline(xintercept = c(tstat), \n             color = \"red\")\n```\n\n::: {.cell-output-display}\n![](Day11_bsta511_code_files/figure-html/unnamed-chunk-10-1.png){width=480}\n:::\n:::\n\n\nCalculate the _p_-value:\n\n\n\n# Step 5: Conclusion to hypothesis test\n\n\\begin{align}\nH_0:& \\mu_{caff} - \\mu_{ctrl} = \\\\\nH_A:& \\mu_{caff} - \\mu_{ctrl} \\\\\n\\end{align}\n\n* Recall the $p$-value = 0.00397\n* Use $\\alpha$ = 0.05.\n* Do we reject or fail to reject $H_0$?\n\n__Conclusion statement__:\n\n* Stats class conclusion\n    * There is sufficient evidence that the (population) difference in mean finger taps/min with vs. without caffeine is greater than 0 ( $p$-value = 0.004).\n\n* More realistic manuscript conclusion: \n    * The mean finger taps/min were 244.8 (SD = 2.4) and 248.3 (SD = 2.2) for the control and caffeine groups, and the increase of 3.5 taps/min was statistically significant ( $p$-value = 0.004).\n\n\n# 95% CI for the mean difference in cholesterol levels\n\n\n::: {.cell}\n::: {.cell-output-display}\n```{=html}\n<div id=\"aemdzdrexs\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#aemdzdrexs table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#aemdzdrexs thead, #aemdzdrexs tbody, #aemdzdrexs tfoot, #aemdzdrexs tr, #aemdzdrexs td, #aemdzdrexs th {\n  border-style: none;\n}\n\n#aemdzdrexs p {\n  margin: 0;\n  padding: 0;\n}\n\n#aemdzdrexs .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#aemdzdrexs .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#aemdzdrexs .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#aemdzdrexs .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#aemdzdrexs .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#aemdzdrexs .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aemdzdrexs .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#aemdzdrexs .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#aemdzdrexs .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#aemdzdrexs .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#aemdzdrexs .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#aemdzdrexs .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#aemdzdrexs .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#aemdzdrexs .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#aemdzdrexs .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#aemdzdrexs .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#aemdzdrexs .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#aemdzdrexs .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#aemdzdrexs .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aemdzdrexs .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#aemdzdrexs .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#aemdzdrexs .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#aemdzdrexs .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aemdzdrexs .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#aemdzdrexs .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#aemdzdrexs .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aemdzdrexs .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aemdzdrexs .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#aemdzdrexs .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aemdzdrexs .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#aemdzdrexs .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#aemdzdrexs .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#aemdzdrexs .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aemdzdrexs .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#aemdzdrexs .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#aemdzdrexs .gt_left {\n  text-align: left;\n}\n\n#aemdzdrexs .gt_center {\n  text-align: center;\n}\n\n#aemdzdrexs .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#aemdzdrexs .gt_font_normal {\n  font-weight: normal;\n}\n\n#aemdzdrexs .gt_font_bold {\n  font-weight: bold;\n}\n\n#aemdzdrexs .gt_font_italic {\n  font-style: italic;\n}\n\n#aemdzdrexs .gt_super {\n  font-size: 65%;\n}\n\n#aemdzdrexs .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#aemdzdrexs .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#aemdzdrexs .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#aemdzdrexs .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#aemdzdrexs .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#aemdzdrexs .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#aemdzdrexs .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"Group\">Group</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_center\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"variable\">variable</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"n\">n</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"mean\">mean</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"sd\">sd</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"Group\" class=\"gt_row gt_left\">Caffeine</td>\n<td headers=\"variable\" class=\"gt_row gt_center\">Taps</td>\n<td headers=\"n\" class=\"gt_row gt_right\">10</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">248.3</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">2.214</td></tr>\n    <tr><td headers=\"Group\" class=\"gt_row gt_left\">NoCaffeine</td>\n<td headers=\"variable\" class=\"gt_row gt_center\">Taps</td>\n<td headers=\"n\" class=\"gt_row gt_right\">10</td>\n<td headers=\"mean\" class=\"gt_row gt_right\">244.8</td>\n<td headers=\"sd\" class=\"gt_row gt_right\">2.394</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n\n\nCI for $\\mu_{caff} - \\mu_{ctrl}$:\n\n$$\\bar{x}_{caff} - \\bar{x}_{ctrl} \\pm t^* \\cdot \\sqrt{\\frac{s_{caff}^2}{n_{caff}}+\\frac{s_{ctrl}^2}{n_{ctrl}}}$$\n\n\n__Interpretation__:  \nWe are 95% confident that the (population) difference in mean finger taps/min between the caffeine and control groups is between 1.167 mg/dL and 5.833 mg/dL.\n\n* _Based on the CI, is there evidence that drinking caffeine made a difference in finger taps/min? Why or why not?_\n\n# R\n\n## R: 2-sample t-test (with long data)\n\n* The `CaffTaps` data are in a *long* format, meaning that \n    * all of the outcome values are in one column and \n    * another column indicates which group the values are from\n* This is a common format for data from multiple samples, especially if the sample sizes are different.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n(Taps_2ttest <- t.test(formula = Taps ~ Group, alternative = \"greater\", data = CaffTaps))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tWelch Two Sample t-test\n\ndata:  Taps by Group\nt = 3.3942, df = 17.89, p-value = 0.001628\nalternative hypothesis: true difference in means between group Caffeine and group NoCaffeine is greater than 0\n95 percent confidence interval:\n 1.711272      Inf\nsample estimates:\n  mean in group Caffeine mean in group NoCaffeine \n                   248.3                    244.8 \n```\n:::\n:::\n\n\n\n### `tidy` the `t.test` output\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# use tidy command from broom package for briefer output that's a tibble\ntidy(Taps_2ttest) %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"myyydydjfv\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#myyydydjfv table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#myyydydjfv thead, #myyydydjfv tbody, #myyydydjfv tfoot, #myyydydjfv tr, #myyydydjfv td, #myyydydjfv th {\n  border-style: none;\n}\n\n#myyydydjfv p {\n  margin: 0;\n  padding: 0;\n}\n\n#myyydydjfv .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#myyydydjfv .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#myyydydjfv .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#myyydydjfv .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#myyydydjfv .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#myyydydjfv .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#myyydydjfv .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#myyydydjfv .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#myyydydjfv .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#myyydydjfv .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#myyydydjfv .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#myyydydjfv .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#myyydydjfv .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#myyydydjfv .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#myyydydjfv .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#myyydydjfv .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#myyydydjfv .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#myyydydjfv .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#myyydydjfv .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#myyydydjfv .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#myyydydjfv .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#myyydydjfv .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#myyydydjfv .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#myyydydjfv .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#myyydydjfv .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#myyydydjfv .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#myyydydjfv .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#myyydydjfv .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#myyydydjfv .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#myyydydjfv .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#myyydydjfv .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#myyydydjfv .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#myyydydjfv .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#myyydydjfv .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#myyydydjfv .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#myyydydjfv .gt_left {\n  text-align: left;\n}\n\n#myyydydjfv .gt_center {\n  text-align: center;\n}\n\n#myyydydjfv .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#myyydydjfv .gt_font_normal {\n  font-weight: normal;\n}\n\n#myyydydjfv .gt_font_bold {\n  font-weight: bold;\n}\n\n#myyydydjfv .gt_font_italic {\n  font-style: italic;\n}\n\n#myyydydjfv .gt_super {\n  font-size: 65%;\n}\n\n#myyydydjfv .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#myyydydjfv .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#myyydydjfv .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#myyydydjfv .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#myyydydjfv .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#myyydydjfv .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#myyydydjfv .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate1\">estimate1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate2\">estimate2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">3.5</td>\n<td headers=\"estimate1\" class=\"gt_row gt_right\">248.3</td>\n<td headers=\"estimate2\" class=\"gt_row gt_right\">244.8</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.394168</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.001627703</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">17.89012</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">1.711272</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">Inf</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Welch Two Sample t-test</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">greater</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n* Pull the p-value:\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntidy(Taps_2ttest)$p.value  # we can pull specific values from the tidy output\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.001627703\n```\n:::\n:::\n\n\n\n## R: 2-sample t-test (with wide data)\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# make CaffTaps data wide: pivot_wider needs an ID column so that it \n# knows how to \"match\" values from the Caffeine and NoCaffeine groups\nCaffTaps_wide <- CaffTaps %>% \n  mutate(id = rep(1:10, 2)) %>% #  \"fake\" IDs for pivot_wider step\n  pivot_wider(names_from = \"Group\",\n              values_from = \"Taps\")\nglimpse(CaffTaps_wide)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 10\nColumns: 3\n$ id         <int> 1, 2, 3, 4, 5, 6, 7, 8, 9, 10\n$ Caffeine   <dbl> 246, 248, 250, 252, 248, 250, 246, 248, 245, 250\n$ NoCaffeine <dbl> 242, 245, 244, 248, 247, 248, 242, 244, 246, 242\n```\n:::\n\n```{.r .cell-code}\nt.test(x = CaffTaps_wide$Caffeine, y = CaffTaps_wide$NoCaffeine, alternative = \"greater\") %>% \n  tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"riwajbitwy\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#riwajbitwy table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#riwajbitwy thead, #riwajbitwy tbody, #riwajbitwy tfoot, #riwajbitwy tr, #riwajbitwy td, #riwajbitwy th {\n  border-style: none;\n}\n\n#riwajbitwy p {\n  margin: 0;\n  padding: 0;\n}\n\n#riwajbitwy .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#riwajbitwy .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#riwajbitwy .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#riwajbitwy .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#riwajbitwy .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#riwajbitwy .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#riwajbitwy .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#riwajbitwy .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#riwajbitwy .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#riwajbitwy .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#riwajbitwy .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#riwajbitwy .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#riwajbitwy .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#riwajbitwy .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#riwajbitwy .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#riwajbitwy .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#riwajbitwy .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#riwajbitwy .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#riwajbitwy .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#riwajbitwy .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#riwajbitwy .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#riwajbitwy .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#riwajbitwy .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#riwajbitwy .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#riwajbitwy .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#riwajbitwy .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#riwajbitwy .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#riwajbitwy .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#riwajbitwy .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#riwajbitwy .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#riwajbitwy .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#riwajbitwy .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#riwajbitwy .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#riwajbitwy .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#riwajbitwy .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#riwajbitwy .gt_left {\n  text-align: left;\n}\n\n#riwajbitwy .gt_center {\n  text-align: center;\n}\n\n#riwajbitwy .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#riwajbitwy .gt_font_normal {\n  font-weight: normal;\n}\n\n#riwajbitwy .gt_font_bold {\n  font-weight: bold;\n}\n\n#riwajbitwy .gt_font_italic {\n  font-style: italic;\n}\n\n#riwajbitwy .gt_super {\n  font-size: 65%;\n}\n\n#riwajbitwy .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#riwajbitwy .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#riwajbitwy .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#riwajbitwy .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#riwajbitwy .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#riwajbitwy .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#riwajbitwy .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate1\">estimate1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate2\">estimate2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">3.5</td>\n<td headers=\"estimate1\" class=\"gt_row gt_right\">248.3</td>\n<td headers=\"estimate2\" class=\"gt_row gt_right\">244.8</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.394168</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.001627703</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">17.89012</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">1.711272</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">Inf</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Welch Two Sample t-test</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">greater</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\n\n## Why are the df's in the R output different?\n\nFrom many slides ago:\n\n* Statistical theory tells us that $t_{\\bar{x}_1 - \\bar{x}_2}$ follows a __student's t-distribution__ with \n    * $df \\approx$ smaller of $n_1-1$ and $n_2-1$\n    * this is a __conservative__ estimate (smaller than actual $df$ )\n\nThe actual degrees of freedom are calculated using  Satterthwaite's method:\n\n$$\\nu = \\frac{[ (s_1^2/n_1) + (s_2^2/n_2) ]^2}\n{(s_1^2/n_1)^2/(n_1 - 1) + (s_2^2/n_2)^2/(n_2-1) }\n= \\frac{ [ SE_1^2 + SE_2^2 ]^2}{ SE_1^4/df_1 + SE_2^4/df_2 }$$\n\n<hr>\n\nVerify the _p_-value in the R output using $\\nu$ = 17.89012:\n\n\n::: {.cell}\n\n```{.r .cell-code}\npt(3.3942, df = 17.89012, lower.tail = FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.001627588\n```\n:::\n:::\n\n\n\n# Pooled standard deviation estimate\n\n* Sometimes we have reasons to believe that the population SD's from the two groups are equal, such as when randomizing participants to two groups\n\n\n* In this case we can use a __pooled SD__:\n\n$$s_{pooled}^2 = \\frac{s_1^2 (n_1-1) + s_2^2 (n_2-1)}{n_1 + n_2 - 2}$$\n\nwhere $n_1$ and $n_2$ are the sample sizes, and $s_1$ and $s_2$ are the sample standard deviations of the two groups \n\n* We use the pooled SD instead of $s_1^2$ and $s_2^2$ when calculating the standard error \n\n$$SE = \\sqrt{\\frac{s_{pooled}^2}{n_1} + \\frac{s_{pooled}^2}{n_2}}= s_{pooled}\\sqrt{\\frac{1}{n_1} + \\frac{1}{n_2}}$$\n\n\n\n__Test statistic__ with pooled SD:\n\n$$t_{\\bar{x}_1 - \\bar{x}_2} = \\frac{\\bar{x}_1 - \\bar{x}_2 -0}{s_{pooled}\\sqrt{\\frac{1}{n_1} + \\frac{1}{n_2}}}$$\n\n__CI__  with pooled SD:\n\n$$(\\bar{x}_1 - \\bar{x}_2) \\pm t^{\\star} \\cdot s_{pooled} \\sqrt{\\frac{1}{n_1} + \\frac{1}{n_2}}$$\n\n* The $t$ distribution degrees of freedom are now:\n$$df = (n_1 - 1) + (n_2 - 1) = n_1 + n_2 - 2.$$\n\n\n\n## R: 2-sample t-test with pooled SD \n\n\n::: {.cell}\n\n```{.r .cell-code}\n# t-test with pooled SD\nt.test(formula = Taps ~ Group, alternative = \"greater\", \n       var.equal = TRUE,  # pooled SD \n       data = CaffTaps) %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"fhrqllobbb\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#fhrqllobbb table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#fhrqllobbb thead, #fhrqllobbb tbody, #fhrqllobbb tfoot, #fhrqllobbb tr, #fhrqllobbb td, #fhrqllobbb th {\n  border-style: none;\n}\n\n#fhrqllobbb p {\n  margin: 0;\n  padding: 0;\n}\n\n#fhrqllobbb .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#fhrqllobbb .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#fhrqllobbb .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#fhrqllobbb .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#fhrqllobbb .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fhrqllobbb .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fhrqllobbb .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#fhrqllobbb .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#fhrqllobbb .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#fhrqllobbb .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#fhrqllobbb .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#fhrqllobbb .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#fhrqllobbb .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#fhrqllobbb .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#fhrqllobbb .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#fhrqllobbb .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#fhrqllobbb .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#fhrqllobbb .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#fhrqllobbb .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fhrqllobbb .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#fhrqllobbb .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#fhrqllobbb .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#fhrqllobbb .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fhrqllobbb .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#fhrqllobbb .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#fhrqllobbb .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fhrqllobbb .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fhrqllobbb .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#fhrqllobbb .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fhrqllobbb .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#fhrqllobbb .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#fhrqllobbb .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fhrqllobbb .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fhrqllobbb .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#fhrqllobbb .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#fhrqllobbb .gt_left {\n  text-align: left;\n}\n\n#fhrqllobbb .gt_center {\n  text-align: center;\n}\n\n#fhrqllobbb .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#fhrqllobbb .gt_font_normal {\n  font-weight: normal;\n}\n\n#fhrqllobbb .gt_font_bold {\n  font-weight: bold;\n}\n\n#fhrqllobbb .gt_font_italic {\n  font-style: italic;\n}\n\n#fhrqllobbb .gt_super {\n  font-size: 65%;\n}\n\n#fhrqllobbb .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#fhrqllobbb .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#fhrqllobbb .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#fhrqllobbb .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#fhrqllobbb .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#fhrqllobbb .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#fhrqllobbb .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate1\">estimate1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate2\">estimate2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">3.5</td>\n<td headers=\"estimate1\" class=\"gt_row gt_right\">248.3</td>\n<td headers=\"estimate2\" class=\"gt_row gt_right\">244.8</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.394168</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.001616497</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">18</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">1.711867</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">Inf</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Two Sample t-test</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">greater</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n\n```{.r .cell-code}\n# t-test without pooled SD\nt.test(formula = Taps ~ Group, alternative = \"greater\", \n       var.equal = FALSE,  # default, NOT pooled SD \n       data = CaffTaps) %>% tidy() %>% gt()\n```\n\n::: {.cell-output-display}\n```{=html}\n<div id=\"iihfsccmtn\" style=\"padding-left:0px;padding-right:0px;padding-top:10px;padding-bottom:10px;overflow-x:auto;overflow-y:auto;width:auto;height:auto;\">\n<style>#iihfsccmtn table {\n  font-family: system-ui, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif, 'Apple Color Emoji', 'Segoe UI Emoji', 'Segoe UI Symbol', 'Noto Color Emoji';\n  -webkit-font-smoothing: antialiased;\n  -moz-osx-font-smoothing: grayscale;\n}\n\n#iihfsccmtn thead, #iihfsccmtn tbody, #iihfsccmtn tfoot, #iihfsccmtn tr, #iihfsccmtn td, #iihfsccmtn th {\n  border-style: none;\n}\n\n#iihfsccmtn p {\n  margin: 0;\n  padding: 0;\n}\n\n#iihfsccmtn .gt_table {\n  display: table;\n  border-collapse: collapse;\n  line-height: normal;\n  margin-left: auto;\n  margin-right: auto;\n  color: #333333;\n  font-size: 16px;\n  font-weight: normal;\n  font-style: normal;\n  background-color: #FFFFFF;\n  width: auto;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #A8A8A8;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #A8A8A8;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n}\n\n#iihfsccmtn .gt_caption {\n  padding-top: 4px;\n  padding-bottom: 4px;\n}\n\n#iihfsccmtn .gt_title {\n  color: #333333;\n  font-size: 125%;\n  font-weight: initial;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-color: #FFFFFF;\n  border-bottom-width: 0;\n}\n\n#iihfsccmtn .gt_subtitle {\n  color: #333333;\n  font-size: 85%;\n  font-weight: initial;\n  padding-top: 3px;\n  padding-bottom: 5px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-color: #FFFFFF;\n  border-top-width: 0;\n}\n\n#iihfsccmtn .gt_heading {\n  background-color: #FFFFFF;\n  text-align: center;\n  border-bottom-color: #FFFFFF;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iihfsccmtn .gt_bottom_border {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iihfsccmtn .gt_col_headings {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n}\n\n#iihfsccmtn .gt_col_heading {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 6px;\n  padding-left: 5px;\n  padding-right: 5px;\n  overflow-x: hidden;\n}\n\n#iihfsccmtn .gt_column_spanner_outer {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: normal;\n  text-transform: inherit;\n  padding-top: 0;\n  padding-bottom: 0;\n  padding-left: 4px;\n  padding-right: 4px;\n}\n\n#iihfsccmtn .gt_column_spanner_outer:first-child {\n  padding-left: 0;\n}\n\n#iihfsccmtn .gt_column_spanner_outer:last-child {\n  padding-right: 0;\n}\n\n#iihfsccmtn .gt_column_spanner {\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: bottom;\n  padding-top: 5px;\n  padding-bottom: 5px;\n  overflow-x: hidden;\n  display: inline-block;\n  width: 100%;\n}\n\n#iihfsccmtn .gt_spanner_row {\n  border-bottom-style: hidden;\n}\n\n#iihfsccmtn .gt_group_heading {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  text-align: left;\n}\n\n#iihfsccmtn .gt_empty_group_heading {\n  padding: 0.5px;\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  vertical-align: middle;\n}\n\n#iihfsccmtn .gt_from_md > :first-child {\n  margin-top: 0;\n}\n\n#iihfsccmtn .gt_from_md > :last-child {\n  margin-bottom: 0;\n}\n\n#iihfsccmtn .gt_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  margin: 10px;\n  border-top-style: solid;\n  border-top-width: 1px;\n  border-top-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 1px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 1px;\n  border-right-color: #D3D3D3;\n  vertical-align: middle;\n  overflow-x: hidden;\n}\n\n#iihfsccmtn .gt_stub {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iihfsccmtn .gt_stub_row_group {\n  color: #333333;\n  background-color: #FFFFFF;\n  font-size: 100%;\n  font-weight: initial;\n  text-transform: inherit;\n  border-right-style: solid;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n  padding-left: 5px;\n  padding-right: 5px;\n  vertical-align: top;\n}\n\n#iihfsccmtn .gt_row_group_first td {\n  border-top-width: 2px;\n}\n\n#iihfsccmtn .gt_row_group_first th {\n  border-top-width: 2px;\n}\n\n#iihfsccmtn .gt_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iihfsccmtn .gt_first_summary_row {\n  border-top-style: solid;\n  border-top-color: #D3D3D3;\n}\n\n#iihfsccmtn .gt_first_summary_row.thick {\n  border-top-width: 2px;\n}\n\n#iihfsccmtn .gt_last_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iihfsccmtn .gt_grand_summary_row {\n  color: #333333;\n  background-color: #FFFFFF;\n  text-transform: inherit;\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iihfsccmtn .gt_first_grand_summary_row {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-top-style: double;\n  border-top-width: 6px;\n  border-top-color: #D3D3D3;\n}\n\n#iihfsccmtn .gt_last_grand_summary_row_top {\n  padding-top: 8px;\n  padding-bottom: 8px;\n  padding-left: 5px;\n  padding-right: 5px;\n  border-bottom-style: double;\n  border-bottom-width: 6px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iihfsccmtn .gt_striped {\n  background-color: rgba(128, 128, 128, 0.05);\n}\n\n#iihfsccmtn .gt_table_body {\n  border-top-style: solid;\n  border-top-width: 2px;\n  border-top-color: #D3D3D3;\n  border-bottom-style: solid;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n}\n\n#iihfsccmtn .gt_footnotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iihfsccmtn .gt_footnote {\n  margin: 0px;\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iihfsccmtn .gt_sourcenotes {\n  color: #333333;\n  background-color: #FFFFFF;\n  border-bottom-style: none;\n  border-bottom-width: 2px;\n  border-bottom-color: #D3D3D3;\n  border-left-style: none;\n  border-left-width: 2px;\n  border-left-color: #D3D3D3;\n  border-right-style: none;\n  border-right-width: 2px;\n  border-right-color: #D3D3D3;\n}\n\n#iihfsccmtn .gt_sourcenote {\n  font-size: 90%;\n  padding-top: 4px;\n  padding-bottom: 4px;\n  padding-left: 5px;\n  padding-right: 5px;\n}\n\n#iihfsccmtn .gt_left {\n  text-align: left;\n}\n\n#iihfsccmtn .gt_center {\n  text-align: center;\n}\n\n#iihfsccmtn .gt_right {\n  text-align: right;\n  font-variant-numeric: tabular-nums;\n}\n\n#iihfsccmtn .gt_font_normal {\n  font-weight: normal;\n}\n\n#iihfsccmtn .gt_font_bold {\n  font-weight: bold;\n}\n\n#iihfsccmtn .gt_font_italic {\n  font-style: italic;\n}\n\n#iihfsccmtn .gt_super {\n  font-size: 65%;\n}\n\n#iihfsccmtn .gt_footnote_marks {\n  font-size: 75%;\n  vertical-align: 0.4em;\n  position: initial;\n}\n\n#iihfsccmtn .gt_asterisk {\n  font-size: 100%;\n  vertical-align: 0;\n}\n\n#iihfsccmtn .gt_indent_1 {\n  text-indent: 5px;\n}\n\n#iihfsccmtn .gt_indent_2 {\n  text-indent: 10px;\n}\n\n#iihfsccmtn .gt_indent_3 {\n  text-indent: 15px;\n}\n\n#iihfsccmtn .gt_indent_4 {\n  text-indent: 20px;\n}\n\n#iihfsccmtn .gt_indent_5 {\n  text-indent: 25px;\n}\n</style>\n<table class=\"gt_table\" data-quarto-disable-processing=\"false\" data-quarto-bootstrap=\"false\">\n  <thead>\n    \n    <tr class=\"gt_col_headings\">\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate\">estimate</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate1\">estimate1</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"estimate2\">estimate2</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"statistic\">statistic</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"p.value\">p.value</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"parameter\">parameter</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.low\">conf.low</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_right\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"conf.high\">conf.high</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"method\">method</th>\n      <th class=\"gt_col_heading gt_columns_bottom_border gt_left\" rowspan=\"1\" colspan=\"1\" scope=\"col\" id=\"alternative\">alternative</th>\n    </tr>\n  </thead>\n  <tbody class=\"gt_table_body\">\n    <tr><td headers=\"estimate\" class=\"gt_row gt_right\">3.5</td>\n<td headers=\"estimate1\" class=\"gt_row gt_right\">248.3</td>\n<td headers=\"estimate2\" class=\"gt_row gt_right\">244.8</td>\n<td headers=\"statistic\" class=\"gt_row gt_right\">3.394168</td>\n<td headers=\"p.value\" class=\"gt_row gt_right\">0.001627703</td>\n<td headers=\"parameter\" class=\"gt_row gt_right\">17.89012</td>\n<td headers=\"conf.low\" class=\"gt_row gt_right\">1.711272</td>\n<td headers=\"conf.high\" class=\"gt_row gt_right\">Inf</td>\n<td headers=\"method\" class=\"gt_row gt_left\">Welch Two Sample t-test</td>\n<td headers=\"alternative\" class=\"gt_row gt_left\">greater</td></tr>\n  </tbody>\n  \n  \n</table>\n</div>\n```\n:::\n:::\n\n\nSimilar output in this case - why??\n\n\n# What's next? \n\nCI's and hypothesis tests for different scenarios:\n\n$$\\text{point estimate} \\pm z^*(or~t^*)\\cdot SE,~~\\text{test stat} = \\frac{\\text{point estimate}-\\text{null value}}{SE}$$\n\nDay | Book | Population <br> parameter | Symbol | Point estimate | Symbol | SE\n--|--|--|--|--|--|--\n10 | 5.1 | Pop mean | $\\mu$ | Sample mean | $\\bar{x}$ | $\\frac{s}{\\sqrt{n}}$\n10 | 5.2 | Pop mean of paired diff | $\\mu_d$ or $\\delta$ | Sample mean of paired diff | $\\bar{x}_{d}$  | **$\\frac{s_d}{\\sqrt{n}}$**\n11 | 5.3 | [Diff in pop <br> means]{style=\"color:green\"} | [$\\mu_1-\\mu_2$]{style=\"color:green\"} | [Diff in sample <br> means]{style=\"color:green\"} | [$\\bar{x}_1 - \\bar{x}_2$]{style=\"color:green\"}  | [**$\\sqrt{\\frac{s_1^2}{n_1} + \\frac{s_2^2}{n_2}}$ or pooled**]{style=\"color:red\"}\n12 | 8.1 | [Pop proportion]{style=\"color:darkblue\"} | [$p$]{style=\"color:darkblue\"} | [Sample prop]{style=\"color:darkblue\"} | [$\\widehat{p}$]{style=\"color:darkblue\"}  | [**???**]{style=\"color:red\"}\n12 | 8.2 | [Diff in pop <br> proportions]{style=\"color:darkblue\"} | [$p_1-p_2$]{style=\"color:darkblue\"} | [Diff in sample <br> proportions]{style=\"color:darkblue\"} | [$\\widehat{p}_1-\\widehat{p}_2$]{style=\"color:darkblue\"} | [**???**]{style=\"color:red\"}\n\n\n# POWER\n\n\n\n# Goals for today \n\n* Critical values & rejection region\n\n* Type I & II errors\n\n* Power\n\n* How to calculate sample size needed for a study?\n\n<hr>\n\n* Material is from \n    * __4.3.4__ Decision errors\n    * __5.4__ Power calculations for a difference of means\n    * plus notes\n\n\n\n## Steps in a Hypothesis Test\n\n1. Set the __[level of significance]{style=\"color:darkorange\"}__ $\\alpha$\n\n1. Specify the __[null]{style=\"color:darkorange\"}__ ( $H_0$ ) and __[alternative]{style=\"color:darkorange\"}__ ( $H_A$ ) __[hypotheses]{style=\"color:darkorange\"}__\n    1. In symbols\n    1. In words\n    1. Alternative: one- or two-sided?\n\n1. Calculate the __[test statistic]{style=\"color:darkorange\"}__. \n\n1. Calculate the __[p-value]{style=\"color:darkorange\"}__ based on the observed test statistic and its sampling distribution\n\n1. Write a __[conclusion]{style=\"color:darkorange\"}__ to the hypothesis test\n    1. Do we reject or fail to reject $H_0$?\n    1. Write a conclusion in the context of the problem\n\n\n\n# Critical values \n\n* __Critical values__ are the cutoff values that determine whether a test statistic is statistically significant or not.\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day11_bsta511_code_files/figure-html/unnamed-chunk-19-1.png){width=480}\n:::\n:::\n\n\n\n* If a test statistic is greater in absolute value than the critical value, we reject $H_0$\n\n* Critical values are determined by \n    * the significance level $\\alpha$, \n    * whether a test is 1- or 2-sided, &\n    * the probability distribution being used to calculate the p-value (such as normal or t-distribution).\n\n* The critical values in the figure should look very familiar! \n    * Where have we used these before?\n\n* How can we calculate the critical values using R?\n\n\n## Rejection region\n\n.pull-left-60[\n* If a test statistic is greater in absolute value than the critical value, we reject $H_0$\n    * In this case the test statistic is in the __rejection region__.\n    * Otherwise it's in the nonrejection region.\n\n* What do rejection regions look like for 2-sided vs. 1-sided tests?\n\n\n\n# Hypothesis Testing \"Errors\" \n\nType I and Type II Errors - Making Mistakes in the Justice System\n\nhttp://www.intuitor.com/statistics/T1T2Errors.html\n\n\n## Type I & II Errors\n\n\n* $\\alpha$ = probability of making a __Type I error__\n    * This is the significance level (usually 0.05)\n    * Should be set before a study starts\n* $\\beta$ = probability of making a __Type II error__\n* Ideally we want\n    * small Type I & II errors and\n    * big power\n\n\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day11_bsta511_code_files/figure-html/unnamed-chunk-20-1.png){width=576}\n:::\n:::\n\n\n\nApplet for visualizing Type I & II errors and power: https://rpsychologist.com/d3/NHST/\n\n## Relationship between Type I & II errors \n\n\n* __Type I vs. Type II error__\n    * Decreasing P(Type I error) leads to \n        * increasing P(Type II error)\n    * We typically keep P(Type I error) = $\\alpha$ set to 0.05\n        \nTry out the applet at https://rpsychologist.com/d3/NHST/\n\n\n\n## Relationship between Type II errors and power\n\n\n* __Power__ = P(correctly rejecting the null hypothesis)\n* Also called the\n    * true positive rate,\n    * probability of detection, or \n    * the _sensitivity_ of a test\n    \n\n* __Power vs. Type II error__\n\n    * Power = 1 - P(Type II error) = 1 - $\\beta$\n\n    * Thus as P(Type II error) decreases, the power increases\n\n    * P(Type II error) = $\\beta$ decreases as the mean of the alternative population gets further away from the mean of the null population (effect size gets bigger).\n\n    * Typically want at least 80% power; 90% power is good\n\n\n\n# Example calculating the power\n\n.pull-left-40[\n* Suppose the mean of the null population is 0 ( $H_0: \\mu=0$ ) with standard error 1\n* Find the power of a 2-sided test if the actual $\\mu=3$, assuming the SE doesn't change.\n\n\n\n::: {.cell}\n::: {.cell-output-display}\n![](Day11_bsta511_code_files/figure-html/unnamed-chunk-21-1.png){width=576}\n:::\n:::\n\n\n\n* Power = $P($Reject $H_0$ when alternative pop is $N(3,1))$\n* When $\\alpha$ = 0.05, we reject $H_0$ when the test statistic z is at least 1.96\n* Thus we need to calculate \n\n$$P(X \\ge 1.96) + P(X \\le -1.96)$$ \n\nwhen $X\\sim N(3,1)$\n\n\n::: {.cell}\n\n```{.r .cell-code}\npnorm(1.96, mean=3, sd=1, lower.tail=FALSE) +\n  pnorm(-1.96, mean=3, sd=1, lower.tail=TRUE)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.8508304\n```\n:::\n:::\n\n\nThe left tail probability `pnorm(-1.96, mean=3, sd=1, lower.tail=TRUE)` is essentially 0 in this case.\n\n\n# Sample size calculation for testing one proportion\n\n* Recall in our sports betting example that the null $p_0=0.36$ and the observed proportion was 0.35. \n* The _p_-value from the hypothesis test was not significant.\n* How big would the sample size $n$ need to be in order for the _p_-value to be significant?\n\n\n\nCalculate $n$ when given $\\alpha$, power ( $1-\\beta$ ), \"true\" alternative proportion $p$, and null $p_0$:\n\n$$n=p(1-p)\\left(\\frac{z_{1-\\alpha/2}+z_{1-\\beta}}{p-p_0}\\right)^2$$\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- 0.35\np0 <- 0.36\nalpha <- 0.05\nbeta <- 0.20  #power=1-beta; want >=80% power\nn <- p*(1-p)*((qnorm(1-alpha/2)+qnorm(1-beta))/\n                (p-p0))^2\nceiling(n) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17857\n```\n:::\n:::\n\n\n_We would need a sample size of at least 17857!_\n\n\n### Power calculation for testing one proportion\n\nConversely, we can calculate how much power we had in our example given the sample size of 269.\n\n\n* Calculate power given $\\alpha$, $n$, \"true\" alternative proportion $p$, and null $p_0$\n    * where $\\Phi$ is the probability for a standard normal distribution \n\n$$1-\\beta=\n\t\t\t\\Phi\\left(z-z_{1-\\alpha/2}\\right)+\\Phi\\left(-z-z_{1-\\alpha/2}\\right)\n\t\t\t\\quad ,\\quad z=\\frac{p-p_0}{\\sqrt{\\frac{p(1-p)}{n}}}$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\np <- 0.35; p0 <- 0.36\nalpha <- 0.05\nn <- 269\nz=(p-p0)/sqrt(p*(1-p)/n)\nPower=pnorm(z-qnorm(1-alpha/2))+\n  pnorm(-z-qnorm(1-alpha/2))\nPower\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.06365242\n```\n:::\n:::\n\n\nIf the population proportion is 0.35 instead of 0.36, we only have a 6.4% chance of correctly rejecting $H_0$ when the sample size is 269.\n\n\n\n\n \n\n## Software for power and sample size calculations \n\n* R package `pwr` for basic statistical tests\n    * https://cran.r-project.org/web/packages/pwr/vignettes/pwr-vignette.html\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(pwr)\n# sample size for one proportion test\np.out <- pwr.p.test(\n  h = ES.h(p1 = 0.36, p2 = 0.35),\n  sig.level = 0.05, \n  power = 0.80, \n  alternative = \"two.sided\")\np.out\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     proportion power calculation for binomial distribution (arcsine transformation) \n\n              h = 0.02089854\n              n = 17971.09\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(p.out)\n```\n\n::: {.cell-output-display}\n![](Day11_bsta511_code_files/figure-html/unnamed-chunk-26-1.png){width=576}\n:::\n:::\n\n\n### Power for one proportion test\n\nLeave out the parameter that you want to solve for\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# library(pwr)\n# power for one proportion test\np.power <- pwr.p.test(\n  h = ES.h(p1 = 0.36, p2 = 0.35),\n  sig.level = 0.05, \n  # power = 0.80, \n  n = 269,\n  alternative = \"two.sided\")\np.power\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     proportion power calculation for binomial distribution (arcsine transformation) \n\n              h = 0.02089854\n              n = 269\n      sig.level = 0.05\n          power = 0.06356445\n    alternative = two.sided\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(p.power)\n```\n\n::: {.cell-output-display}\n![](Day11_bsta511_code_files/figure-html/unnamed-chunk-28-1.png){width=576}\n:::\n:::\n\n\n\n\n# Sample size calculation for testing one mean\n\n* Recall in our body temperature example that the null $\\mu_0=98.6$ and the observed mean was 98.25. \n* The _p_-value from the hypothesis test was highly significant.\n* How big does the sample size $n$ need to be in order for the _p_-value to be _just barely_ significant?\n\n\n\nCalculate $n$ when given $\\alpha$, power ( $1-\\beta$ ), \"true\" alternative mean $\\mu$, and null $\\mu_0$, _assuming_ the test statistic is normal (instead of t-distribution):\n\n$$n=\\left(s\\frac{z_{1-\\alpha/2}+z_{1-\\beta}}{\\mu-\\mu_0}\\right)^2$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu=98.25\nmu0=98.6\nsd=0.73\nalpha=0.05\nbeta=0.20\nn=(sd*(qnorm(1-alpha/2)+qnorm(1-beta))/(mu-mu0))^2\nceiling(n)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 35\n```\n:::\n:::\n\n\n\n_We would only need a sample size of 35!_ However, this is an under-estimate since we used the normal instead of t-distribution.\n\nSee http://powerandsamplesize.com/Calculators/Test-1-Mean/1-Sample-Equality.\n\n\n\n## Power calculation for testing one mean\n\nConversely, we can calculate how much power we had in our example given the sample size of 130.\n\n* Calculate power given $\\alpha$, $n$, \"true\" alternative mean $\\mu$, and null $\\mu_0$, _assuming_ the test statistic is normal (instead of t-distribution)\n    * where $\\Phi$ is the probability for a standard normal distribution \n\n$$1-\\beta=\n\t\t\\Phi\\left(z-z_{1-\\alpha/2}\\right)+\\Phi\\left(-z-z_{1-\\alpha/2}\\right)\n\t\t\\quad ,\\quad z=\\frac{\\mu-\\mu_0}{s/\\sqrt{n}}$$\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmu=98.25; mu0=98.6; sd=0.73; alpha=0.05; n=130\nz=(mu-mu0)/sd*sqrt(n)\nPower=pnorm(z-qnorm(1-alpha/2))+\n  pnorm(-z-qnorm(1-alpha/2))\nPower\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.9997731\n```\n:::\n:::\n\n\n\n\nIf the population mean is 98.2 instead of 98.6, we have a 99.98% chance of correctly rejecting $H_0$ when the sample size is 130.  \nWe would say this was over powered.\n\n\n\n## Software for power and sample size calculations \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# sample size for one mean test\nt.n <- power.t.test(  # base R power function\n  delta = 98.6-98.25, sd=0.73,\n    sig.level = 0.05, \n  power = 0.80, \n  type = \"one.sample\")\nt.n\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     One-sample t test power calculation \n\n              n = 36.11207\n          delta = 0.35\n             sd = 0.73\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(t.n)\n```\n\n::: {.cell-output-display}\n![](Day11_bsta511_code_files/figure-html/unnamed-chunk-32-1.png){width=576}\n:::\n:::\n\n\n\n### Sample size for one mean test\n\nLeave out the parameter that you want to solve for\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# sample size for one proportion test\nt.power <- power.t.test(\n  delta = 98.6-98.25, sd=0.73,\n    sig.level = 0.05, \n  # power = 0.80, \n  n = 130,\n  type = \"one.sample\")\nt.power\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     One-sample t test power calculation \n\n              n = 130\n          delta = 0.35\n             sd = 0.73\n      sig.level = 0.05\n          power = 0.9997354\n    alternative = two.sided\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(t.power)\n```\n\n::: {.cell-output-display}\n![](Day11_bsta511_code_files/figure-html/unnamed-chunk-34-1.png){width=576}\n:::\n:::\n\n\n \n\n# Testing difference of two independent means\n\n* See section 5.4 of text for formulas\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt2.n <- power.t.test(\n  delta = 98.6-98.25, sd=0.73,\n    sig.level = 0.05, \n  power = 0.80, \n  type = \"two.sample\") \nt2.n\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     Two-sample t test power calculation \n\n              n = 69.26206\n          delta = 0.35\n             sd = 0.73\n      sig.level = 0.05\n          power = 0.8\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(t2.n)\n```\n\n::: {.cell-output-display}\n![](Day11_bsta511_code_files/figure-html/unnamed-chunk-36-1.png){width=576}\n:::\n:::\n\n\n\n\n\n## Software: sample size for two means test\n\nLeave out the parameter that you want to solve for\n\n\n::: {.cell}\n\n```{.r .cell-code}\nt2.power <- power.t.test(\n  delta = 98.6-98.25, sd=0.73,\n    sig.level = 0.05, \n  # power = 0.80, \n  n = 130,\n  type = \"two.sample\")\nt2.power\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n     Two-sample t test power calculation \n\n              n = 130\n          delta = 0.35\n             sd = 0.73\n      sig.level = 0.05\n          power = 0.9706928\n    alternative = two.sided\n\nNOTE: n is number in *each* group\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(t2.power)\n```\n\n::: {.cell-output-display}\n![](Day11_bsta511_code_files/figure-html/unnamed-chunk-38-1.png){width=576}\n:::\n:::\n\n\n\n\n# More software for power and sample size calculations: PASS \n\n* PASS is a very powerful (& expensive) software that does power and sample size calculations for many advanced statistical modeling techniques.\n    * Even if you don't have access to PASS, their [documentation](https://www.ncss.com/software/pass/pass-documentation/) is very good and free online.\n    * Documentation includes formulas and references.\n    * PASS documentation for [one proportion tests](https://www.ncss.com/software/pass/pass-documentation/#Proportions), which includes more advanced formulas.\n    * PASS documentation for [one mean tests](https://www.ncss.com/software/pass/pass-documentation/#Means)\n\n\nhttps://www.ncss.com/wp-content/themes/ncss/pdf/Procedures/PASS/One-Sample_T-Tests.pdf\n\n\n# OCTRI-BERD power & sample size presentations\n\n\n* __Power and Sample Size 101__\n  * Presented by Meike Niederhausen; Feb 4, 2021\n  * Slides: http://bit.ly/PSS-101\n  * [Recording](https://echo360.org/lesson/604d5c35-465d-415e-b62f-f57f9c2d5780/classroom)\n\n* __Power and Sample Size for Clinical Trials: An Introduction__\n  * Presented by Yiyi Chen; Feb 18, 2021\n  * Slides: http://bit.ly/PSS-ClinicalTrials\n  * [Recording](https://echo360.org/lesson/9a21deb8-258d-4305-bdc9-7effdc35e719/classroom)\n\n\n* __Planning a Study with Power and Sample Size Considerations in Mind__\n  * Presented by David Yanez; May 29, 2019\n  * [Slides](https://www.ohsu.edu/sites/default/files/2019-12/PowerAndSampleSize_29MAY2019.pdf)\n  * [Recording](https://echo360.org/lesson/44c9a3e9-b8ec-4042-84d8-4758cc779a1f/classroom)\n\n\n\n\n\n\n",
    "supporting": [
      "Day11_bsta511_code_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}