---
title: "Projects in RStudio"
subtitle: "BSTA 511/611"
author: "Meike Niederhausen, PhD"
institute: "OHSU-PSU School of Public Health"
format: 
  html:
    link-external-newwindow: true
    toc: true
execute:
  echo: true
  freeze: auto  # re-render only when source changes
# editor: visual
editor_options: 
  chunk_output_type: console
---

```{r}
#| label: "setup"
#| include: false
knitr::opts_chunk$set(echo = TRUE, fig.height=3, fig.width=5, message = F)
```



* I *highly, highly* recommend using R projects to organize your analyses and make it easier to load data files and also save output.
* When you create an R project on your computer, the project is associated with the folder (directory) you created it in. 
  * This folder becomes the location of the R workspace you're working in, and RStudio's point of reference from where to load files from and save files to. 
* I create separate projects for every analysis or homework assignment (and hence separate folders to store them in).
* You can run multiple sessions of RStudio by opening different projects, and the environments (or workspaces) of each are working independently of each other. 


# Learn more about projects and why you should *always* be using them

Below are various resources to learn more about RStudio "projects."

* [RStudio Projects and Working Directories: A Beginner’s Guide](https://www.r-bloggers.com/2020/01/rstudio-projects-and-working-directories-a-beginners-guide/)
    * From R-bloggers website
    * TOC
        * What is a RStudio project, and why?
        * Easy file path referencing with RStudio projects
        * Structuring your working directory 
        * Further reading 
* Posit's (RStudio's) directions on creating projects
  * https://support.rstudio.com/hc/en-us/articles/200526207-Using-RStudio-Projects
  * This page provides concise directions, but not much motivation on why you should be using projects. 
* R for Data Science
    * Excellent book for learning R for data science by by Hadley Wickham and Garrett Grolemund
    * See Chapter 8: Workflow: projects (https://r4ds.had.co.nz/workflow-projects.html) for 
      * [What is real?](https://r4ds.had.co.nz/workflow-projects.html#what-is-real)
      * [Where does your analysis live?](https://r4ds.had.co.nz/workflow-projects.html#where-does-your-analysis-live)
      * [Paths and directories](https://r4ds.had.co.nz/workflow-projects.html#paths-and-directories)
      * [RStudio projects](https://r4ds.had.co.nz/workflow-projects.html#rstudio-projects)
      * [Summary](https://r4ds.had.co.nz/workflow-projects.html#summary)

* Jenny Bryant's STAT 545 class notes
    * Check out Chapter 2 R basics and workflows https://stat545.com/r-basics.html
    * Section 2.2: [Workspace and working directory](https://stat545.com/r-basics.html#workspace-and-working-directory)
    * Section 2.3: [RStudio projects](https://stat545.com/r-basics.html#rprojs)

# YouTube videos on how to create an R project

This video demonstrates how to create an R project, and how to open RStudio using the project file. 

* _The Basics of Projects in RStudio_ by Sam Burer  
https://www.youtube.com/watch?v=hKoSJGWnFFA
* _Introduction to RStudio Projects_ by Michael Seaman https://www.youtube.com/watch?v=wqOme7xsZvs


